"use client";

import Link from "next/link";
import { useState } from "react";
import { MessageSquare, Sparkles, X } from "lucide-react";
import type { ReviewsPageData } from "@/lib/reviews/reviews-page-data";
import { ReviewerAvatar, ReviewsTable, RvCard, StarRating } from "@/components/reviews/reviews-ui";

export function ReviewsUnansweredTab({ data, businessId }: { data: ReviewsPageData; businessId: string }) {
  const [tipDismissed, setTipDismissed] = useState(false);
  const [selectedId, setSelectedId] = useState(data.unanswered[0]?.id ?? "");
  const selected = data.unanswered.find((r) => r.id === selectedId) ?? data.unanswered[0];

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap gap-3">
        {["Last 90 days", "All", "All", "All"].map((label, i) => (
          <select key={i} className="rounded-lg border border-zinc-200 px-3 py-1.5 text-sm">
            <option>{["Date", "Rating", "Source", "Urgency"][i]}: {label}</option>
          </select>
        ))}
        <button type="button" className="text-sm text-zinc-500 hover:text-zinc-700">Clear filters</button>
      </div>

      <div className="grid gap-6 xl:grid-cols-3">
        <div className="space-y-4 xl:col-span-2">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-base font-semibold text-zinc-900">Unanswered Reviews ({data.unanswered.length})</h3>
              <p className="text-sm text-zinc-500">Prioritized by urgency and time waiting (oldest first).</p>
            </div>
            <select className="rounded-lg border border-zinc-200 px-3 py-1.5 text-sm">
              <option>Sort: Oldest</option>
            </select>
          </div>
          <RvCard className="!p-0 overflow-hidden">
            <ReviewsTable rows={data.unanswered.slice(0, 8)} mode="urgency" />
          </RvCard>
          <p className="text-xs text-zinc-500">
            Showing 1–{Math.min(8, data.unanswered.length)} of {data.unanswered.length} reviews
          </p>
        </div>

        <div className="space-y-4">
          <RvCard>
            <div className="mb-3 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-emerald-600" />
                <h3 className="text-sm font-semibold text-zinc-900">AI Suggested Replies</h3>
              </div>
              <button type="button" className="rounded-lg bg-emerald-600 px-2 py-1 text-xs font-medium text-white">
                Create Reply Tasks
              </button>
            </div>
            {selected ? (
              <>
                <div className="flex items-center gap-2 border-b border-zinc-100 pb-3">
                  <ReviewerAvatar name={selected.reviewerName} />
                  <div>
                    <p className="font-medium text-zinc-900">{selected.reviewerName}</p>
                    <StarRating rating={selected.rating} />
                  </div>
                </div>
                <p className="mt-3 text-sm text-zinc-600 line-clamp-3">{selected.reviewText}</p>
                <div className="mt-3 rounded-lg border border-emerald-100 bg-emerald-50/50 p-3 text-sm text-zinc-700">
                  <p className="text-xs font-medium text-emerald-700">Generated by AI</p>
                  <p className="mt-2">
                    Thank you for your wonderful review, {selected.reviewerName.split(" ")[0]}! We&apos;re thrilled our team
                    could help. We appreciate you taking the time to share your experience.
                  </p>
                </div>
                <div className="mt-3 flex flex-wrap gap-2">
                  <button type="button" className="rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-medium text-white">Use Reply</button>
                  <button type="button" className="rounded-lg border border-zinc-200 px-3 py-1.5 text-xs font-medium">Customize</button>
                  <button type="button" className="text-xs font-medium text-emerald-600">Regenerate</button>
                </div>
              </>
            ) : (
              <p className="text-sm text-zinc-500">No unanswered reviews — great job!</p>
            )}
          </RvCard>

          <RvCard>
            <h3 className="text-sm font-semibold text-zinc-900">Unanswered Impact (Last 90 Days)</h3>
            <dl className="mt-4 space-y-3 text-sm">
              <div className="flex justify-between">
                <dt className="text-zinc-500">Est. rating impact</dt>
                <dd className="font-semibold text-red-600">-0.18</dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-zinc-500">At risk of churn</dt>
                <dd className="font-semibold">{data.kpis.urgentCount} reviews</dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-zinc-500">Revenue at risk</dt>
                <dd className="font-semibold">$1,420 <span className="text-xs font-normal text-zinc-500">Est.</span></dd>
              </div>
            </dl>
            <button type="button" className="mt-4 text-sm font-medium text-emerald-600">
              Learn how faster replies improve results →
            </button>
          </RvCard>

          <RvCard>
            <div className="flex items-center gap-2">
              <MessageSquare className="h-4 w-4 text-emerald-600" />
              <h3 className="text-sm font-semibold text-zinc-900">Suggested Reply Tasks</h3>
            </div>
            <p className="mt-2 text-sm text-zinc-600">{data.unanswered.length} reviews need a response</p>
            <Link href={`/businesses/${businessId}/review-requests?tab=tracking`} className="mt-2 inline-block text-sm font-medium text-emerald-600">
              View tasks →
            </Link>
          </RvCard>
        </div>
      </div>

      {!tipDismissed && (
        <div className="flex items-center justify-between gap-4 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm">
          <p className="text-emerald-900">
            <strong>Tip:</strong> Reviews waiting more than 7 days are 2.6× more likely to be negative.
          </p>
          <button type="button" className="shrink-0 font-medium text-emerald-700">Learn best practices →</button>
          <button type="button" onClick={() => setTipDismissed(true)} className="shrink-0 rounded p-1 hover:bg-emerald-100">
            <X className="h-4 w-4 text-emerald-700" />
          </button>
        </div>
      )}
    </div>
  );
}
