"use client";

import Link from "next/link";
import { useState } from "react";
import { MessageSquare, Sparkles, X } from "lucide-react";
import type { ReviewListItem, ReviewsPageData } from "@/lib/reviews/reviews-page-data";
import { ReviewDetailDrawer } from "@/components/reviews/review-detail-drawer";
import { ReviewerAvatar, ReviewsTable, RvCard, StarRating } from "@/components/reviews/reviews-ui";
import { dashboardCardTitle, dashboardControl, dashboardMicro } from "@/components/overview/dashboard-ui";
import { cn } from "@/lib/utils";

export function ReviewsUnansweredTab({ data, businessId }: { data: ReviewsPageData; businessId: string }) {
  const [tipDismissed, setTipDismissed] = useState(false);
  const [selectedId, setSelectedId] = useState(data.unanswered[0]?.id ?? "");
  const [selectedReview, setSelectedReview] = useState<ReviewListItem | null>(null);
  const selected = data.unanswered.find((r) => r.id === selectedId) ?? data.unanswered[0];

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap gap-2">
        {["Last 90 days", "All", "All", "All"].map((label, i) => (
          <select key={i} className={cn(dashboardControl, "px-3 text-[13px]")}>
            <option>{["Date", "Rating", "Source", "Urgency"][i]}: {label}</option>
          </select>
        ))}
        <button type="button" className="text-[12px] text-zinc-500 hover:text-zinc-700">Clear filters</button>
      </div>

      <div className="grid gap-4 xl:grid-cols-3">
        <div className="space-y-3 xl:col-span-2">
          <div className="flex items-center justify-between gap-2">
            <div>
              <h3 className={dashboardCardTitle}>Unanswered Reviews ({data.unanswered.length})</h3>
              <p className={dashboardMicro}>Prioritized by urgency and time waiting (oldest first). Click a row to read the full review.</p>
            </div>
            <select className={cn(dashboardControl, "px-3 text-[13px]")}>
              <option>Sort: Oldest</option>
            </select>
          </div>
          <RvCard className="!p-0 overflow-hidden">
            <ReviewsTable
              rows={data.unanswered.slice(0, 8)}
              mode="urgency"
              onViewReview={(row) => {
                setSelectedId(row.id);
                setSelectedReview(row);
              }}
            />
          </RvCard>
          <p className={dashboardMicro}>
            Showing 1–{Math.min(8, data.unanswered.length)} of {data.unanswered.length} reviews
          </p>
        </div>

        <div className="space-y-3">
          <RvCard>
            <div className="mb-2.5 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Sparkles className="h-3.5 w-3.5 text-emerald-600" />
                <h3 className={dashboardCardTitle}>AI Suggested Replies</h3>
              </div>
              <button type="button" className="rounded-lg bg-emerald-600 px-2 py-1 text-[11px] font-medium text-white">
                Create Reply Tasks
              </button>
            </div>
            {selected ? (
              <>
                <div className="flex items-center gap-2 border-b border-zinc-100 pb-2.5">
                  <ReviewerAvatar name={selected.reviewerName} size="sm" />
                  <div>
                    <p className="text-[13px] font-medium text-zinc-900">{selected.reviewerName}</p>
                    <StarRating rating={selected.rating} />
                  </div>
                </div>
                <p className="mt-2 text-[13px] text-zinc-600 line-clamp-3">{selected.reviewText}</p>
                <button
                  type="button"
                  onClick={() => setSelectedReview(selected)}
                  className="mt-1.5 text-[12px] font-medium text-emerald-600 hover:text-emerald-700"
                >
                  Read full review →
                </button>
                <div className="mt-2 rounded-lg border border-emerald-100 bg-emerald-50/50 p-2.5 text-[13px] text-zinc-700">
                  <p className="text-[11px] font-medium text-emerald-700">Generated by AI</p>
                  <p className="mt-2">
                    Thank you for your wonderful review, {selected.reviewerName.split(" ")[0]}! We&apos;re thrilled our team
                    could help. We appreciate you taking the time to share your experience.
                  </p>
                </div>
                <div className="mt-2 flex flex-wrap gap-1.5">
                  <button type="button" className="rounded-lg bg-emerald-600 px-2.5 py-1 text-[11px] font-medium text-white">Use Reply</button>
                  <button type="button" className="rounded-lg border border-zinc-200 px-2.5 py-1 text-[11px] font-medium">Customize</button>
                  <button type="button" className="text-[11px] font-medium text-emerald-600">Regenerate</button>
                </div>
              </>
            ) : (
              <p className={dashboardMicro}>No unanswered reviews — great job!</p>
            )}
          </RvCard>

          <RvCard>
            <h3 className={dashboardCardTitle}>Unanswered Impact (Last 90 Days)</h3>
            <dl className="mt-2 space-y-2 text-[13px]">
              <div className="flex justify-between">
                <dt className="text-zinc-500">Est. rating impact</dt>
                <dd className="font-semibold text-red-600">-0.18</dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-zinc-500">At risk of churn</dt>
                <dd className="font-semibold">{data.kpis.urgentCount} reviews</dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-zinc-500">Revenue at risk</dt>
                <dd className="font-semibold">$1,420 <span className="text-xs font-normal text-zinc-500">Est.</span></dd>
              </div>
            </dl>
            <button type="button" className="mt-3 text-[12px] font-medium text-emerald-600">
              Learn how faster replies improve results →
            </button>
          </RvCard>

          <RvCard>
            <div className="flex items-center gap-2">
              <MessageSquare className="h-3.5 w-3.5 text-emerald-600" />
              <h3 className={dashboardCardTitle}>Suggested Reply Tasks</h3>
            </div>
            <p className={`mt-1.5 ${dashboardMicro}`}>{data.unanswered.length} reviews need a response</p>
            <Link href={`/businesses/${businessId}/review-requests?tab=tracking`} className="mt-1.5 inline-block text-[12px] font-medium text-emerald-600">
              View tasks →
            </Link>
          </RvCard>
        </div>
      </div>

      {!tipDismissed && (
        <div className="flex items-center justify-between gap-3 rounded-lg border border-emerald-200 bg-emerald-50 px-3.5 py-2.5 text-[13px]">
          <p className="text-emerald-900">
            <strong>Tip:</strong> Reviews waiting more than 7 days are 2.6× more likely to be negative.
          </p>
          <button type="button" className="shrink-0 font-medium text-emerald-700">Learn best practices →</button>
          <button type="button" onClick={() => setTipDismissed(true)} className="shrink-0 rounded p-1 hover:bg-emerald-100">
            <X className="h-4 w-4 text-emerald-700" />
          </button>
        </div>
      )}

      <ReviewDetailDrawer review={selectedReview} onClose={() => setSelectedReview(null)} />
    </div>
  );
}
