import type { CompetitorIntelligenceDashboardData } from "@/components/reviews/competitor-intelligence-dashboard";

export const COMPETITOR_INTELLIGENCE_PREVIEW_BUSINESS_ID = "preview-competitor-intelligence";

export const competitorIntelligencePreviewData: CompetitorIntelligenceDashboardData = {
  businessId: COMPETITOR_INTELLIGENCE_PREVIEW_BUSINESS_ID,
  businessName: "A-Team Junk Removal",
  dateRangeLabel: "May 10 – Jun 8, 2025",
  requiredPaceOverride: 36,
  leaderboardRows: [
    // #1 Drain Masters — top competitor, 375 total, 33 in 30d
    {
      id: "drain-masters",
      name: "Drain Masters",
      isYou: false,
      totalReviews: 375,
      rating: 4.7,
      reviews30: 33,
      reviews60: 63,
      reviews90: 96,
      reviewsPerMonth: 32.0,
      momentumLabel: "Accelerating",
      responseRate: 76,
      responseSpeedDaysAvg: 2.4,
      deltas: { reviews30: 8, reviews60: 15, reviews90: 22 },
    },
    // #2 You — A-Team Junk Removal — green row
    {
      id: COMPETITOR_INTELLIGENCE_PREVIEW_BUSINESS_ID,
      name: "A-Team Junk Removal",
      isYou: true,
      totalReviews: 327,
      rating: 4.6,
      reviews30: 24,
      reviews60: 42,
      reviews90: 71,
      reviewsPerMonth: 23.7,
      momentumLabel: "Accelerating",
      responseRate: 82,
      responseSpeedDaysAvg: 1.8,
      deltas: { reviews30: 9, reviews60: 18, reviews90: 34 },
    },
    // #3
    {
      id: "clearflow-pros",
      name: "ClearFlow Pros",
      isYou: false,
      totalReviews: 298,
      rating: 4.7,
      reviews30: 19,
      reviews60: 37,
      reviews90: 61,
      reviewsPerMonth: 20.3,
      momentumLabel: "Stable",
      responseRate: 68,
      responseSpeedDaysAvg: 3.2,
      deltas: { reviews30: 2, reviews60: 4, reviews90: 6 },
    },
    // #4
    {
      id: "rapid-rooter",
      name: "Rapid Rooter",
      isYou: false,
      totalReviews: 244,
      rating: 4.4,
      reviews30: 13,
      reviews60: 31,
      reviews90: 45,
      reviewsPerMonth: 15.0,
      momentumLabel: "Slowing",
      responseRate: 51,
      responseSpeedDaysAvg: 5.6,
      deltas: { reviews30: -3, reviews60: 2, reviews90: 5 },
    },
    // #5
    {
      id: "pipe-rescue",
      name: "Pipe Rescue",
      isYou: false,
      totalReviews: 181,
      rating: 4.5,
      reviews30: 15,
      reviews60: 26,
      reviews90: 39,
      reviewsPerMonth: 13.0,
      momentumLabel: "Recovering",
      responseRate: 63,
      responseSpeedDaysAvg: 4.1,
      deltas: { reviews30: 4, reviews60: 5, reviews90: 7 },
    },
  ],
  gapRows: [
    {
      competitorId: "drain-masters",
      competitorName: "Drain Masters",
      // reviewGap 48 (375 - 327)
      totalGap: 48,
      // velocityGap -9 (you 24 - them 33 = -9)
      monthlyVelocityGap: -9,
      neededToCatch: 49,
      pace3Months: 75,
      pace6Months: 102,
      pace12Months: 156,
      // estMonths 4.2 — at required pace (+12) you'd gain 3/mo net
      estimatedCatchUp: "4.2 mo",
      estimatedCatchUpDate: "2025-10-12",
      estimatedCatchUpMonths: 4.2,
      warning: null,
      gapExpanding: false,
    },
    {
      competitorId: "clearflow-pros",
      competitorName: "ClearFlow Pros",
      totalGap: -29,
      monthlyVelocityGap: -5,
      neededToCatch: 0,
      pace3Months: -44,
      pace6Months: -59,
      pace12Months: -89,
      estimatedCatchUp: "Caught up",
      estimatedCatchUpDate: "2025-06-08",
      estimatedCatchUpMonths: 0,
      warning: null,
      gapExpanding: false,
    },
    {
      competitorId: "rapid-rooter",
      competitorName: "Rapid Rooter",
      totalGap: -83,
      monthlyVelocityGap: -11,
      neededToCatch: 0,
      pace3Months: -116,
      pace6Months: -149,
      pace12Months: -215,
      estimatedCatchUp: "Caught up",
      estimatedCatchUpDate: "2025-06-08",
      estimatedCatchUpMonths: 0,
      warning: null,
      gapExpanding: false,
    },
  ],
  catchUpForecast: [
    { competitor: "Drain Masters", monthsToCatchUp: 4.2, reviewsNeededPerMonth: 36 },
    { competitor: "ClearFlow Pros", monthsToCatchUp: 0, reviewsNeededPerMonth: 24 },
  ],
  complaintPatterns: [
    { theme: "Late Arrival", competitorMentions: 18, yourMentions: 4, gap: 14 },
    { theme: "Mess Left Behind", competitorMentions: 13, yourMentions: 2, gap: 11 },
    { theme: "Unclear Pricing", competitorMentions: 10, yourMentions: 3, gap: 7 },
  ],
  positioningOpportunities: [
    {
      title: "Position against late-arrival complaints",
      description: "Highlight confirmed arrival windows and day-of text updates in review requests.",
      sourceTheme: "Late Arrival",
    },
    {
      title: "Promote clean sweep policy",
      description: "Competitors get complaints about mess left behind; reinforce cleanup in replies and sales copy.",
      sourceTheme: "Mess Left Behind",
    },
  ],
  opportunities: [
    "Ask every same-day pickup customer for a Google review within 2 hours.",
    "Promote cleanup and sweep-through language in response templates.",
    "Target 36 reviews/month to catch Drain Masters in ~4 months.",
  ],
  opportunityItems: [
    {
      icon: "check",
      label: "Ask every same-day pickup customer for a Google review within 2 hours.",
    },
    {
      icon: "star",
      label: "Promote cleanup and sweep-through language in review response templates.",
    },
    {
      icon: "chat",
      label: "Target 36 reviews/month to catch Drain Masters in approximately 4 months.",
    },
  ],
  platformPresence: [
    {
      platform: "Google",
      reviews: 327,
      rating: 4.6,
      status: "Connected",
      verified: true,
      note: "Primary review source via Google Business Profile.",
    },
    {
      platform: "Facebook",
      reviews: 89,
      rating: 4.5,
      status: "Estimated",
      verified: false,
      note: "Estimated from public signals. Connect Facebook to verify.",
    },
    {
      platform: "Yelp",
      reviews: 43,
      rating: 4.3,
      status: "Estimated",
      verified: false,
      note: "Estimated from public signals. Connect Yelp to verify.",
    },
  ],
  strengths: {
    positive: [
      { label: "Professional crew", count: 38 },
      { label: "Same-day service", count: 34 },
      { label: "Fair pricing", count: 29 },
      { label: "Careful removal", count: 21 },
    ],
    negative: [
      { label: "Arrival window", count: 5 },
      { label: "Follow-up scheduling", count: 3 },
    ],
    competitorPositive: [
      { label: "Emergency availability", count: 44 },
      { label: "Weekend appointments", count: 36 },
      { label: "Text updates", count: 31 },
    ],
    competitorNegative: [
      { label: "Late Arrival", count: 18 },
      { label: "Mess Left Behind", count: 13 },
      { label: "Unclear Pricing", count: 10 },
    ],
    serviceGaps: [
      { label: "Emergency availability", yourMentions: 11, competitorMentions: 44, gap: 33 },
      { label: "Weekend appointments", yourMentions: 9, competitorMentions: 36, gap: 27 },
      { label: "Text updates", yourMentions: 8, competitorMentions: 31, gap: 23 },
    ],
    frequentlyPraisedServices: [
      { term: "garage cleanout", count: 24 },
      { term: "appliance removal", count: 19 },
      { term: "construction debris", count: 15 },
    ],
    frequentlyMentionedEmployees: [
      { term: "Marcus", count: 8 },
      { term: "Tony", count: 6 },
    ],
  },
  contentComparison: {
    you: {
      avgLength: 148,
      pctWithText: 74,
      locationTerms: 46,
      serviceTerms: 92,
      employeeMentions: 18,
      pctGeneric: 18,
      pctDetailed: 41,
    },
    competitors: {
      avgLength: 116,
      pctWithText: 68,
      locationTerms: 39,
      serviceTerms: 81,
      employeeMentions: 12,
      pctGeneric: 27,
      pctDetailed: 33,
    },
  },
  reviewsFeed: [
    {
      id: "preview-you-1",
      reviewerName: "Sarah M.",
      rating: 5,
      reviewText: "Same-day pickup and the crew was careful with our garage cleanout. Highly recommend.",
      reviewDate: "2025-06-06",
      publishedAt: "2025-06-06T14:00:00.000Z",
      firstObservedAt: "2025-06-06T15:00:00.000Z",
      relativeDate: "2 days ago",
      source: "google",
      tags: ["Same-day", "Professionalism", "Garage cleanout"],
      replied: true,
      ownerResponseText: "Thank you Sarah — glad we could help the same day!",
      isTarget: true,
      businessName: "A-Team Junk Removal",
      competitorId: null,
      daysWaiting: null,
      urgency: null,
      isNew: true,
      resolved: false,
      resolvedAt: null,
    },
    {
      id: "preview-drain-1",
      reviewerName: "Mike T.",
      rating: 5,
      reviewText: "Drain Masters showed up fast and fixed the clog the same afternoon. Friendly techs.",
      reviewDate: "2025-06-05",
      publishedAt: "2025-06-05T11:00:00.000Z",
      firstObservedAt: "2025-06-05T12:00:00.000Z",
      relativeDate: "3 days ago",
      source: "google",
      tags: ["Speed", "Friendly", "Same Day"],
      replied: true,
      ownerResponseText: "Thanks Mike!",
      isTarget: false,
      businessName: "Drain Masters",
      competitorId: "drain-masters",
      daysWaiting: null,
      urgency: null,
      isNew: true,
      resolved: false,
      resolvedAt: null,
    },
    {
      id: "preview-drain-2",
      reviewerName: "Laura K.",
      rating: 2,
      reviewText: "Hard to reach on the phone and scheduling took three days. Price was higher than quoted.",
      reviewDate: "2025-06-03",
      publishedAt: "2025-06-03T09:00:00.000Z",
      firstObservedAt: "2025-06-03T10:00:00.000Z",
      relativeDate: "5 days ago",
      source: "google",
      tags: ["Hard to reach", "Scheduling", "Price"],
      replied: false,
      ownerResponseText: null,
      isTarget: false,
      businessName: "Drain Masters",
      competitorId: "drain-masters",
      daysWaiting: 5,
      urgency: "medium",
      isNew: false,
      resolved: false,
      resolvedAt: null,
    },
    {
      id: "preview-clear-1",
      reviewerName: "Chris P.",
      rating: 4,
      reviewText: "ClearFlow Pros did a solid job. Communication could be clearer on arrival window.",
      reviewDate: "2025-06-02",
      publishedAt: "2025-06-02T16:00:00.000Z",
      firstObservedAt: "2025-06-02T17:00:00.000Z",
      relativeDate: "6 days ago",
      source: "google",
      tags: ["Communication", "Arrival window"],
      replied: true,
      ownerResponseText: "Appreciate the feedback Chris.",
      isTarget: false,
      businessName: "ClearFlow Pros",
      competitorId: "clearflow-pros",
      daysWaiting: null,
      urgency: null,
      isNew: false,
      resolved: false,
      resolvedAt: null,
    },
    {
      id: "preview-rapid-1",
      reviewerName: "Dana R.",
      rating: 5,
      reviewText: "Rapid Rooter was professional and cleaned up afterward. Would use again.",
      reviewDate: "2025-06-01",
      publishedAt: "2025-06-01T13:00:00.000Z",
      firstObservedAt: "2025-06-01T14:00:00.000Z",
      relativeDate: "7 days ago",
      source: "google",
      tags: ["Professionalism", "Cleanup"],
      replied: false,
      ownerResponseText: null,
      isTarget: false,
      businessName: "Rapid Rooter",
      competitorId: "rapid-rooter",
      daysWaiting: 7,
      urgency: "high",
      isNew: false,
      resolved: false,
      resolvedAt: null,
    },
  ],
};
