import type { CompetitorIntelligenceDashboardData } from "@/components/reviews/competitor-intelligence-dashboard";

export const COMPETITOR_INTELLIGENCE_PREVIEW_BUSINESS_ID = "preview-competitor-intelligence";

export const competitorIntelligencePreviewData: CompetitorIntelligenceDashboardData = {
  businessId: COMPETITOR_INTELLIGENCE_PREVIEW_BUSINESS_ID,
  businessName: "A-Team Junk Removal",
  dateRangeLabel: "May 27 - Jun 25, 2024",
  leaderboardRows: [
    {
      id: "drain-masters",
      name: "Drain Masters",
      isYou: false,
      totalReviews: 542,
      rating: 4.8,
      reviews30: 31,
      reviews60: 58,
      reviews90: 88,
      reviewsPerMonth: 29.3,
      momentumLabel: "Accelerating",
      responseRate: 76,
      responseSpeedDaysAvg: 2.4,
      deltas: { reviews30: 7, reviews60: 12, reviews90: 18 },
    },
    {
      id: COMPETITOR_INTELLIGENCE_PREVIEW_BUSINESS_ID,
      name: "A-Team Junk Removal",
      isYou: true,
      totalReviews: 327,
      rating: 4.6,
      reviews30: 24,
      reviews60: 42,
      reviews90: 71,
      reviewsPerMonth: 23.7,
      momentumLabel: "Accelerating",
      responseRate: 82,
      responseSpeedDaysAvg: 1.8,
      deltas: { reviews30: 5, reviews60: 9, reviews90: 14 },
    },
    {
      id: "clearflow-pros",
      name: "ClearFlow Pros",
      isYou: false,
      totalReviews: 298,
      rating: 4.7,
      reviews30: 19,
      reviews60: 37,
      reviews90: 61,
      reviewsPerMonth: 20.3,
      momentumLabel: "Stable",
      responseRate: 68,
      responseSpeedDaysAvg: 3.2,
      deltas: { reviews30: 2, reviews60: 4, reviews90: 6 },
    },
    {
      id: "rapid-rooter",
      name: "Rapid Rooter",
      isYou: false,
      totalReviews: 244,
      rating: 4.4,
      reviews30: 13,
      reviews60: 31,
      reviews90: 45,
      reviewsPerMonth: 15,
      momentumLabel: "Slowing",
      responseRate: 51,
      responseSpeedDaysAvg: 5.6,
      deltas: { reviews30: -3, reviews60: 2, reviews90: 5 },
    },
    {
      id: "pipe-rescue",
      name: "Pipe Rescue",
      isYou: false,
      totalReviews: 181,
      rating: 4.5,
      reviews30: 15,
      reviews60: 26,
      reviews90: 39,
      reviewsPerMonth: 13,
      momentumLabel: "Recovering",
      responseRate: 63,
      responseSpeedDaysAvg: 4.1,
      deltas: { reviews30: 4, reviews60: 5, reviews90: 7 },
    },
  ],
  gapRows: [
    {
      competitorId: "drain-masters",
      competitorName: "Drain Masters",
      totalGap: 215,
      monthlyVelocityGap: 7,
      neededToCatch: 216,
      pace3Months: 236,
      pace6Months: 257,
      pace12Months: 299,
      estimatedCatchUp: "Not at current pace",
      estimatedCatchUpDate: null,
      estimatedCatchUpMonths: null,
      warning: "Drain Masters is adding 7 more reviews per month, so the gap is widening.",
      gapExpanding: true,
    },
    {
      competitorId: "clearflow-pros",
      competitorName: "ClearFlow Pros",
      totalGap: -29,
      monthlyVelocityGap: -5,
      neededToCatch: 0,
      pace3Months: -44,
      pace6Months: -59,
      pace12Months: -89,
      estimatedCatchUp: "Caught up",
      estimatedCatchUpDate: "2024-06-25",
      estimatedCatchUpMonths: 0,
      warning: null,
      gapExpanding: false,
    },
    {
      competitorId: "rapid-rooter",
      competitorName: "Rapid Rooter",
      totalGap: -83,
      monthlyVelocityGap: -11,
      neededToCatch: 0,
      pace3Months: -116,
      pace6Months: -149,
      pace12Months: -215,
      estimatedCatchUp: "Caught up",
      estimatedCatchUpDate: "2024-06-25",
      estimatedCatchUpMonths: 0,
      warning: null,
      gapExpanding: false,
    },
  ],
  complaintPatterns: [
    { theme: "Late Arrival", competitorMentions: 18, yourMentions: 4, gap: 14 },
    { theme: "Mess Left Behind", competitorMentions: 13, yourMentions: 2, gap: 11 },
    { theme: "Unclear Pricing", competitorMentions: 10, yourMentions: 3, gap: 7 },
  ],
  positioningOpportunities: [
    {
      title: "Position against late-arrival complaints",
      description: "Highlight confirmed arrival windows and day-of text updates in review requests.",
      sourceTheme: "Late Arrival",
    },
    {
      title: "Promote clean sweep policy",
      description: "Competitors get complaints about mess left behind; reinforce cleanup in replies and sales copy.",
      sourceTheme: "Mess Left Behind",
    },
  ],
  opportunities: [
    "Ask every same-day pickup customer for a Google review within 2 hours.",
    "Promote cleanup and sweep-through language in response templates.",
    "Target 40 reviews/month to stop Drain Masters from widening the gap.",
  ],
  strengths: {
    positive: [
      { label: "Professional crew", count: 38 },
      { label: "Same-day service", count: 34 },
      { label: "Fair pricing", count: 29 },
      { label: "Careful removal", count: 21 },
    ],
    negative: [
      { label: "Arrival window", count: 5 },
      { label: "Follow-up scheduling", count: 3 },
    ],
    competitorPositive: [
      { label: "Emergency availability", count: 44 },
      { label: "Weekend appointments", count: 36 },
      { label: "Text updates", count: 31 },
    ],
    competitorNegative: [
      { label: "Late Arrival", count: 18 },
      { label: "Mess Left Behind", count: 13 },
      { label: "Unclear Pricing", count: 10 },
    ],
    serviceGaps: [
      { label: "Emergency availability", yourMentions: 11, competitorMentions: 44, gap: 33 },
      { label: "Weekend appointments", yourMentions: 9, competitorMentions: 36, gap: 27 },
      { label: "Text updates", yourMentions: 8, competitorMentions: 31, gap: 23 },
    ],
    frequentlyPraisedServices: [
      { term: "garage cleanout", count: 24 },
      { term: "appliance removal", count: 19 },
      { term: "construction debris", count: 15 },
    ],
    frequentlyMentionedEmployees: [
      { term: "Marcus", count: 8 },
      { term: "Tony", count: 6 },
    ],
  },
  contentComparison: {
    you: {
      avgLength: 148,
      pctWithText: 74,
      locationTerms: 46,
      serviceTerms: 92,
      employeeMentions: 18,
      pctGeneric: 18,
      pctDetailed: 41,
    },
    competitors: {
      avgLength: 116,
      pctWithText: 68,
      locationTerms: 39,
      serviceTerms: 81,
      employeeMentions: 12,
      pctGeneric: 27,
      pctDetailed: 33,
    },
  },
};
