import type { MomentumLabel } from "@/lib/reviews/metrics";
import type { MarketInsights } from "@/lib/reviews/market-insights";

export const REVIEW_MOMENTUM_PREVIEW_BUSINESS_ID = "preview-momentum";

const market: MarketInsights = {
  velocityTrend: "accelerating",
  velocityTrendLabel: "Gaining ground",
  targetSharePct30d: 24,
  marketActivityLevel: "low",
  marketActivityLabel: "Low Activity",
  marketReviews30d: 30,
  entityCount: 4,
  currentWeeklyPace: 0.5,
  recommendedWeeklyPace: 2,
  weeklyPaceGap: 1.5,
  top3AvgWeeklyPace: 2.3,
  weeklyPace: [
    { name: "You", entityType: "target", avgReviewsPerWeek: 0.5 },
    { name: "Junk King", entityType: "competitor", avgReviewsPerWeek: 3.2 },
    { name: "College Hunks", entityType: "competitor", avgReviewsPerWeek: 2.1 },
  ],
  shareOfNewReviews30d: [
    { name: "You", entityType: "target", sharePct: 24, reviews30d: 2 },
    { name: "Junk King", entityType: "competitor", sharePct: 38, reviews30d: 14 },
    { name: "College Hunks", entityType: "competitor", sharePct: 22, reviews30d: 8 },
    { name: "LoadUp", entityType: "competitor", sharePct: 16, reviews30d: 6 },
  ],
  reviewStreakWeeks: 2,
  daysWithoutReview: null,
  recencyStatus: "warning",
};

export const reviewMomentumPreviewPayload = {
  run: {
    id: "run-preview",
    status: "complete",
    ai_summary:
      "You are gaining reviews but still trail the market leader on 30-day velocity. Focus on post-job review requests to close the weekly pace gap.",
    warnings: [] as string[],
    created_at: new Date().toISOString(),
  },
  entities: [
    {
      id: "target",
      entity_type: "target",
      name: "Junk Removal Woodbridge",
      rating_current: 5,
      total_reviews_current: 127,
      reviews_7d: 1,
      reviews_30d: 2,
      reviews_90d: 8,
      avg_reviews_per_week: 0.5,
      days_since_last_review: 12,
      momentum_label: "Accelerating" as MomentumLabel,
      momentum_score: 62,
      gap_to_top3_30d: 4,
      recommended_weekly_target: 2,
      metrics_json: {
        dailyExact7d: [
          { date: "2026-07-07", count: 0, exact: true },
          { date: "2026-07-08", count: 1, exact: true },
          { date: "2026-07-09", count: 0, exact: true },
          { date: "2026-07-10", count: 0, exact: true },
          { date: "2026-07-11", count: 0, exact: true },
          { date: "2026-07-12", count: 1, exact: true },
          { date: "2026-07-13", count: 0, exact: true },
        ],
        dailyCounts30d: Array.from({ length: 30 }, (_, i) => ({
          date: `2026-06-${String(14 + (i % 16)).padStart(2, "0")}`,
          count: [0, 1, 0, 0, 2, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 2, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1][i] ?? 0,
        })),
        weeklyBuckets8to30: [
          { label: "Week 1", count: 1, bucketed: true },
          { label: "Week 2", count: 0, bucketed: true },
          { label: "Week 3", count: 2, bucketed: true },
        ],
        trendBuckets90d: [
          { label: "W1", count: 1 },
          { label: "W2", count: 2 },
          { label: "W3", count: 1 },
          { label: "W4", count: 3 },
          { label: "W5", count: 2 },
          { label: "W6", count: 2 },
        ],
        weekdayHeatmap: [
          { day: "Mon", count: 2 },
          { day: "Tue", count: 1 },
          { day: "Wed", count: 3 },
          { day: "Thu", count: 0 },
          { day: "Fri", count: 2 },
          { day: "Sat", count: 4 },
          { day: "Sun", count: 1 },
        ],
        velocityAvailable: true,
        marketInsights: market,
      },
    },
    {
      id: "c1",
      entity_type: "competitor",
      name: "Junk King",
      rating_current: 4.9,
      total_reviews_current: 890,
      reviews_7d: 4,
      reviews_30d: 14,
      reviews_90d: 38,
      avg_reviews_per_week: 3.2,
      days_since_last_review: 3,
      momentum_label: "Exploding" as MomentumLabel,
      momentum_score: 88,
      gap_to_top3_30d: null,
      metrics_json: { velocityAvailable: true },
    },
    {
      id: "c2",
      entity_type: "competitor",
      name: "College Hunks",
      rating_current: 4.8,
      total_reviews_current: 412,
      reviews_7d: 2,
      reviews_30d: 8,
      reviews_90d: 22,
      avg_reviews_per_week: 2.1,
      days_since_last_review: 5,
      momentum_label: "Healthy" as MomentumLabel,
      momentum_score: 71,
      gap_to_top3_30d: null,
      metrics_json: { velocityAvailable: true },
    },
  ],
  tasks: [
    {
      id: "t1",
      title: "Send review requests after jobs",
      description: "Trigger SMS/email within 24 hours of completed hauls.",
      priority: "high",
      impact: "high",
      effort: "low",
      status: "open",
    },
    {
      id: "t2",
      title: "Reply to unanswered reviews",
      description: "Two recent 5-star reviews are still unreplied.",
      priority: "medium",
      impact: "medium",
      effort: "low",
      status: "open",
    },
    {
      id: "t3",
      title: "Match competitor review pace",
      description: "Aim for 2 reviews per week for the next month.",
      priority: "high",
      impact: "high",
      effort: "medium",
      status: "open",
    },
    {
      id: "t4",
      title: "Add review QR at job site",
      description: "Print QR cards for crews to hand customers after pickup.",
      priority: "low",
      impact: "medium",
      effort: "low",
      status: "open",
    },
  ],
};
