import type { ReviewInsightsData } from "@/lib/reviews/review-insights-data";

export const REVIEW_INSIGHTS_PREVIEW_BUSINESS_ID = "preview-review-insights";

export const reviewInsightsPreviewData: ReviewInsightsData = {
  businessId: REVIEW_INSIGHTS_PREVIEW_BUSINESS_ID,
  businessName: "A-Team Junk Removal",
  dataUpdatedAt: "Jun 8, 2025, 2:22 PM",
  metrics: {
    positiveThemeMentions: 12,
    negativeThemeMentions: 8,
    totalReviewText: 284,
    pctWithText: 87,
    avgReviewLength: 128,
    reviewsWithPhotos: 42,
    photosPct: 13,
    employeeMentions: 23,
  },
  themes: {
    positive: [
      { label: "Professionalism", count: 68, pct: 26 },
      { label: "On-Time Arrival", count: 55, pct: 21 },
      { label: "Clear Communication", count: 45, pct: 17 },
      { label: "Clean Work Area", count: 38, pct: 15 },
      { label: "Fair Pricing", count: 31, pct: 12 },
      { label: "Fast Service", count: 24, pct: 9 },
    ],
    negative: [
      { label: "Didn't Answer Phone", count: 12, pct: 24 },
      { label: "Scheduling Issues", count: 9, pct: 18 },
      { label: "Quote Mismatch", count: 7, pct: 14 },
      { label: "Late Arrival", count: 6, pct: 12 },
      { label: "Communication Gap", count: 5, pct: 10 },
      { label: "Missed Callbacks", count: 4, pct: 8 },
    ],
    emerging: [
      { label: "Garage Cleanout", count: 16, pct: 7, delta: 8 },
      { label: "Estate Cleanout", count: 11, pct: 5, delta: 6 },
      { label: "Text Updates", count: 9, pct: 4, delta: 4 },
    ],
    themeFrequencyOverTime: [
      { label: "Professionalism", recent30: 24, prior30: 18, delta: 6 },
      { label: "On-Time Arrival", recent30: 19, prior30: 14, delta: 5 },
      { label: "Clear Communication", recent30: 16, prior30: 12, delta: 4 },
      { label: "Fair Pricing", recent30: 12, prior30: 14, delta: -2 },
      { label: "Didn't Answer Phone", recent30: 6, prior30: 3, delta: 3 },
      { label: "Scheduling Issues", recent30: 4, prior30: 5, delta: -1 },
    ],
    themeTrend30d: [
      { date: "May 10", positive: 18, negative: 5, neutral: 6 },
      { date: "May 17", positive: 23, negative: 3, neutral: 8 },
      { date: "May 24", positive: 21, negative: 6, neutral: 7 },
      { date: "May 31", positive: 27, negative: 2, neutral: 9 },
      { date: "Jun 7", positive: 31, negative: 4, neutral: 7 },
    ],
    competitorThemes: [
      { label: "Professionalism", yourCount: 68, competitorCount: 52, competitorAvg: 17.3, gap: -50.7 },
      { label: "On-Time Arrival", yourCount: 55, competitorCount: 44, competitorAvg: 14.7, gap: -40.3 },
      { label: "Fair Pricing", yourCount: 31, competitorCount: 41, competitorAvg: 13.7, gap: -17.3 },
      { label: "Didn't Answer Phone", yourCount: 12, competitorCount: 29, competitorAvg: 9.7, gap: -2.3 },
      { label: "Scheduling Issues", yourCount: 9, competitorCount: 22, competitorAvg: 7.3, gap: 1.7 },
    ],
    competitorComparison: [
      { theme: "Professionalism", you: 26, topCompetitor: 18, secondCompetitor: 22, industryAvg: 20 },
      { theme: "On-Time Arrival", you: 21, topCompetitor: 15, secondCompetitor: 12, industryAvg: 16 },
      { theme: "Clear Communication", you: 17, topCompetitor: 11, secondCompetitor: 15, industryAvg: 14 },
      { theme: "Fair Pricing", you: 12, topCompetitor: 14, secondCompetitor: 10, industryAvg: 13 },
      { theme: "Cleanliness", you: 15, topCompetitor: 20, secondCompetitor: 17, industryAvg: 18 },
      { theme: "Didn't Answer Phone", you: 24, topCompetitor: 11, secondCompetitor: 19, industryAvg: 15 },
    ],
    services: [
      { label: "Junk Removal", count: 142, pct: 43 },
      { label: "Furniture Removal", count: 56, pct: 17 },
      { label: "Appliance Removal", count: 38, pct: 12 },
      { label: "Mattress Disposal", count: 24, pct: 7 },
      { label: "Garage Cleanout", count: 21, pct: 6 },
      { label: "Estate Cleanout", count: 18, pct: 6 },
    ],
    locations: [
      { label: "Woodbridge, VA", count: 187, pct: 57 },
      { label: "Prince William County", count: 52, pct: 16 },
      { label: "Manassas, VA", count: 34, pct: 10 },
      { label: "Dale City, VA", count: 28, pct: 9 },
      { label: "Lake Ridge, VA", count: 16, pct: 5 },
      { label: "Dumfries, VA", count: 11, pct: 3 },
    ],
  },
  servicesAndKeywords: [
    { keyword: "junk removal", count: 63 },
    { keyword: "garage cleanout", count: 28 },
    { keyword: "furniture haul away", count: 24 },
    { keyword: "same-day pickup", count: 22 },
    { keyword: "hot tub removal", count: 15 },
    { keyword: "estate cleanout", count: 13 },
    { keyword: "appliance removal", count: 11 },
    { keyword: "yard debris", count: 9 },
  ],
  categorizedKeywords: {
    services: [
      { keyword: "junk removal", count: 63 },
      { keyword: "garage cleanout", count: 28 },
      { keyword: "furniture haul away", count: 24 },
      { keyword: "hot tub removal", count: 15 },
      { keyword: "estate cleanout", count: 13 },
    ],
    cities: [
      { keyword: "Woodbridge", count: 48 },
      { keyword: "Manassas", count: 22 },
      { keyword: "Dale City", count: 18 },
      { keyword: "Dumfries", count: 11 },
    ],
    employees: [
      { keyword: "Marcus", count: 14 },
      { keyword: "Elena", count: 11 },
      { keyword: "Staff / crew", count: 10 },
      { keyword: "David", count: 7 },
    ],
    pricing: [
      { keyword: "clear quote", count: 18 },
      { keyword: "fair price", count: 14 },
      { keyword: "upfront pricing", count: 11 },
    ],
    speed: [
      { keyword: "same-day", count: 22 },
      { keyword: "on time", count: 18 },
      { keyword: "quick pickup", count: 12 },
    ],
    communication: [
      { keyword: "text updates", count: 15 },
      { keyword: "called ahead", count: 13 },
      { keyword: "responsive", count: 11 },
    ],
  },
  responsePerformance: {
    responseRate: 87,
    totalWithText: 284,
    answered: 247,
    unansweredPositive: 22,
    unansweredNegative: 9,
    unansweredNeutral: 6,
    avgResponseTimeDays: 1.4,
    positiveResponseRate: 91,
    negativeResponseRate: 79,
    oldestUnansweredAt: "2025-05-14",
    oldestUnansweredDays: 25,
  },
  responseQuality: {
    genericResponseSuspected: 11,
    genericResponsePct: 4,
    qualitySummary: {
      personalizedPct: 76,
      genericPct: 4,
      copyPastePct: 9,
      defensiveCount: 2,
      addressesIssuePct: 72,
      offersResolutionPct: 65,
    },
    rows: [
      {
        reviewId: "rev-preview-001",
        personalized: true,
        generic: false,
        copyPasteClusterId: null,
        defensive: false,
        addressesIssue: true,
        offersResolution: true,
        evidence: ["Mentions customer's garage cleanout", "Offers direct callback"],
      },
      {
        reviewId: "rev-preview-002",
        personalized: false,
        generic: true,
        copyPasteClusterId: "cluster-3",
        defensive: false,
        addressesIssue: false,
        offersResolution: false,
        evidence: ["Short canned thank-you response"],
      },
      {
        reviewId: "rev-preview-003",
        personalized: true,
        generic: false,
        copyPasteClusterId: null,
        defensive: true,
        addressesIssue: true,
        offersResolution: false,
        evidence: ["Uses policy language", "Acknowledges quote mismatch"],
      },
    ],
  },
};
