import type { ReviewInsightsData } from "@/lib/reviews/review-insights-data";

export const REVIEW_INSIGHTS_PREVIEW_BUSINESS_ID = "preview-review-insights";

export const reviewInsightsPreviewData: ReviewInsightsData = {
  businessId: REVIEW_INSIGHTS_PREVIEW_BUSINESS_ID,
  businessName: "A-Team Junk Removal",
  metrics: {
    positiveThemeMentions: 184,
    negativeThemeMentions: 31,
    totalReviewText: 214,
    avgReviewLength: 186,
    reviewsWithPhotos: null,
    employeeMentions: 42,
  },
  themes: {
    positive: [
      { label: "Professional crew", count: 54, pct: 25 },
      { label: "Same-day service", count: 38, pct: 18 },
      { label: "Clear pricing", count: 31, pct: 14 },
      { label: "Careful cleanup", count: 26, pct: 12 },
      { label: "Friendly communication", count: 22, pct: 10 },
      { label: "Fast scheduling", count: 13, pct: 6 },
    ],
    negative: [
      { label: "Arrival window", count: 12, pct: 6 },
      { label: "Quote mismatch", count: 8, pct: 4 },
      { label: "Missed callbacks", count: 5, pct: 2 },
      { label: "Truck availability", count: 4, pct: 2 },
      { label: "Follow-up needed", count: 2, pct: 1 },
    ],
    emerging: [
      { label: "Garage cleanout", count: 16, pct: 7, delta: 8 },
      { label: "Estate cleanout", count: 11, pct: 5, delta: 6 },
      { label: "Text updates", count: 9, pct: 4, delta: 4 },
    ],
    themeFrequencyOverTime: [
      { label: "Professional crew", recent30: 21, prior30: 15, delta: 6 },
      { label: "Same-day service", recent30: 18, prior30: 12, delta: 6 },
      { label: "Clear pricing", recent30: 14, prior30: 16, delta: -2 },
      { label: "Careful cleanup", recent30: 12, prior30: 8, delta: 4 },
      { label: "Arrival window", recent30: 7, prior30: 4, delta: 3 },
      { label: "Quote mismatch", recent30: 4, prior30: 6, delta: -2 },
    ],
    competitorThemes: [
      { label: "Same-day service", yourCount: 38, competitorCount: 44, competitorAvg: 14.7, gap: -23.3 },
      { label: "Professional crew", yourCount: 54, competitorCount: 36, competitorAvg: 12, gap: -42 },
      { label: "Clear pricing", yourCount: 31, competitorCount: 41, competitorAvg: 13.7, gap: -17.3 },
      { label: "Arrival window", yourCount: 12, competitorCount: 29, competitorAvg: 9.7, gap: -2.3 },
      { label: "Missed callbacks", yourCount: 5, competitorCount: 22, competitorAvg: 7.3, gap: 2.3 },
    ],
  },
  servicesAndKeywords: [
    { keyword: "junk removal", count: 63 },
    { keyword: "garage cleanout", count: 28 },
    { keyword: "furniture haul away", count: 24 },
    { keyword: "same-day pickup", count: 22 },
    { keyword: "hot tub removal", count: 15 },
    { keyword: "estate cleanout", count: 13 },
    { keyword: "appliance removal", count: 11 },
    { keyword: "yard debris", count: 9 },
  ],
  categorizedKeywords: {
    services: [
      { keyword: "junk removal", count: 63 },
      { keyword: "garage cleanout", count: 28 },
      { keyword: "furniture haul away", count: 24 },
      { keyword: "hot tub removal", count: 15 },
      { keyword: "estate cleanout", count: 13 },
    ],
    cities: [
      { keyword: "Arlington", count: 18 },
      { keyword: "Alexandria", count: 16 },
      { keyword: "Falls Church", count: 12 },
      { keyword: "Fairfax", count: 9 },
    ],
    employees: [
      { keyword: "Marcus", count: 14 },
      { keyword: "Elena", count: 11 },
      { keyword: "Staff / crew", count: 10 },
      { keyword: "David", count: 7 },
    ],
    pricing: [
      { keyword: "clear quote", count: 18 },
      { keyword: "fair price", count: 14 },
      { keyword: "upfront pricing", count: 11 },
    ],
    speed: [
      { keyword: "same-day", count: 22 },
      { keyword: "on time", count: 18 },
      { keyword: "quick pickup", count: 12 },
    ],
    communication: [
      { keyword: "text updates", count: 15 },
      { keyword: "called ahead", count: 13 },
      { keyword: "responsive", count: 11 },
    ],
  },
  responsePerformance: {
    responseRate: 87,
    totalWithText: 214,
    answered: 186,
    unansweredPositive: 18,
    unansweredNegative: 7,
    unansweredNeutral: 3,
    avgResponseTimeDays: 1.8,
    positiveResponseRate: 91,
    negativeResponseRate: 76,
    oldestUnansweredAt: "2024-06-03",
    oldestUnansweredDays: 22,
  },
  responseQuality: {
    genericResponseSuspected: 14,
    genericResponsePct: 8,
    qualitySummary: {
      personalizedPct: 72,
      genericPct: 8,
      copyPastePct: 11,
      defensiveCount: 3,
      addressesIssuePct: 68,
      offersResolutionPct: 61,
    },
    rows: [
      {
        reviewId: "rev-preview-001",
        personalized: true,
        generic: false,
        copyPasteClusterId: null,
        defensive: false,
        addressesIssue: true,
        offersResolution: true,
        evidence: ["Mentions customer's garage cleanout", "Offers direct callback"],
      },
      {
        reviewId: "rev-preview-002",
        personalized: false,
        generic: true,
        copyPasteClusterId: "cluster-3",
        defensive: false,
        addressesIssue: false,
        offersResolution: false,
        evidence: ["Short canned thank-you response"],
      },
      {
        reviewId: "rev-preview-003",
        personalized: true,
        generic: false,
        copyPasteClusterId: null,
        defensive: true,
        addressesIssue: true,
        offersResolution: false,
        evidence: ["Uses policy language", "Acknowledges quote mismatch"],
      },
    ],
  },
};
