import type { ReviewListItem, ReviewsPageData } from "@/lib/reviews/reviews-page-data";

function review(
  id: string,
  overrides: Partial<ReviewListItem> & Pick<ReviewListItem, "reviewerName">
): ReviewListItem {
  return {
    id,
    reviewerName: overrides.reviewerName,
    rating: overrides.rating ?? 5,
    reviewText:
      overrides.reviewText ??
      "Great experience from start to finish. The team was professional, on time, and explained everything clearly.",
    reviewDate: overrides.reviewDate ?? "2026-06-18",
    relativeDate: overrides.relativeDate ?? "3 weeks ago",
    source: overrides.source ?? "google",
    tags: overrides.tags ?? ["friendly staff", "clean office"],
    replied: overrides.replied ?? true,
    ownerResponseText: overrides.ownerResponseText ?? null,
    isTarget: overrides.isTarget ?? true,
    businessName: overrides.businessName ?? "Bright Smile Dental",
    competitorId: overrides.competitorId ?? null,
    daysWaiting: overrides.daysWaiting ?? null,
    urgency: overrides.urgency ?? null,
  };
}

export const REVIEWS_PREVIEW_DATA: ReviewsPageData = {
  businessId: "preview",
  businessName: "Bright Smile Dental",
  hasData: true,
  lastSyncedAt: "2026-07-10T12:00:00.000Z",
  kpis: {
    avgRating: 4.8,
    avgRatingDelta: 0.2,
    totalReviews: 123,
    newReviews90d: 18,
    newReviews90dDelta: 4,
    reviewGap: 12,
    responseRate: 92,
    responseRateDelta: 5,
    unanswered90d: 2,
    avgDaysWaiting: 3,
    urgentCount: 1,
  },
  latestTargetReviews: [
    review("r1", { reviewerName: "Sarah Mitchell" }),
    review("r2", { reviewerName: "James Carter", rating: 4 }),
    review("r3", { reviewerName: "Emily Nguyen", replied: false }),
  ],
  competitorActivity: [
    { id: "c1", name: "Downtown Dental", rating: 4.6, newReviews90d: 9, spark: [2, 3, 4, 5, 6, 7, 9] },
    { id: "c2", name: "Family Smiles", rating: 4.4, newReviews90d: 6, spark: [1, 2, 2, 3, 4, 5, 6] },
  ],
  topKeywords: [
    { keyword: "friendly staff", count: 14 },
    { keyword: "short wait", count: 9 },
    { keyword: "clean office", count: 8 },
  ],
  competitorWinningKeywords: [
    { keyword: "Appointment Scheduling", count: 11 },
    { keyword: "Residential Junk", count: 7 },
    { keyword: "Professionalism", count: 7 },
    { keyword: "Safe Driver", count: 5 },
    { keyword: "Quick Response", count: 5 },
    { keyword: "Customer Service", count: 2 },
  ],
  fastestGrowingCompetitor: { name: "Downtown Dental", rating: 4.6, delta: 9 },
  stream: [
    review("s1", { reviewerName: "Sarah Mitchell" }),
    review("s2", { reviewerName: "James Carter", rating: 4, isTarget: false, businessName: "Downtown Dental" }),
    review("s3", { reviewerName: "Emily Nguyen", replied: false }),
    review("s4", { reviewerName: "Michael Brooks", rating: 5 }),
    review("s5", { reviewerName: "Lisa Tran", rating: 3, replied: false }),
    review("s6", { reviewerName: "Chris Allen", rating: 5, isTarget: false, businessName: "Family Smiles" }),
    review("s7", { reviewerName: "Priya Shah", rating: 4 }),
    review("s8", { reviewerName: "Daniel Ortiz", rating: 5 }),
    review("s9", { reviewerName: "Amy Lewis", rating: 2, replied: false }),
    review("s10", { reviewerName: "Kevin Park", rating: 5 }),
    review("s11", { reviewerName: "Rachel Gomez", rating: 5 }),
    review("s12", { reviewerName: "Tom Bradley", rating: 4, isTarget: false, businessName: "Downtown Dental" }),
    review("s13", { reviewerName: "Nina Patel", rating: 5, replied: false }),
    review("s14", { reviewerName: "Oscar Reed", rating: 3 }),
    review("s15", { reviewerName: "Hannah Kim", rating: 5, isTarget: false, businessName: "Family Smiles" }),
    review("s16", { reviewerName: "Marcus Lee", rating: 4 }),
    review("s17", { reviewerName: "Julia Fox", rating: 5 }),
    review("s18", { reviewerName: "Ben Carter", rating: 2, replied: false }),
  ],
  yourReviews: [
    review("y1", { reviewerName: "Sarah Mitchell" }),
    review("y2", { reviewerName: "Emily Nguyen", replied: false }),
    review("y3", { reviewerName: "Michael Brooks", rating: 5 }),
  ],
  competitors: [
    {
      id: "c1",
      name: "SP Top Junk Removal",
      rating: 5,
      avgRating: 5,
      totalReviews: 140,
      newReviews90d: 11,
      newReviewsDeltaPct: 18,
      velocitySpark: [2, 3, 4, 5, 7, 9, 11],
    },
    {
      id: "c2",
      name: "K Sheets Junk Removal",
      rating: 5,
      avgRating: 5,
      totalReviews: 88,
      newReviews90d: 7,
      newReviewsDeltaPct: 4,
      velocitySpark: [1, 2, 2, 3, 4, 5, 7],
    },
    {
      id: "c3",
      name: "Removal expert inc",
      rating: 5,
      avgRating: 5,
      totalReviews: 42,
      newReviews90d: 5,
      newReviewsDeltaPct: -2,
      velocitySpark: [1, 1, 2, 2, 3, 4, 5],
    },
  ],
  competitorReviews: [
    review("cr1", {
      reviewerName: "Lisa Tran",
      rating: 3,
      isTarget: false,
      businessName: "Downtown Dental",
      competitorId: "c1",
    }),
    review("cr2", {
      reviewerName: "Chris Allen",
      rating: 5,
      isTarget: false,
      businessName: "Family Smiles",
      competitorId: "c2",
    }),
    review("cr3", {
      reviewerName: "Tom Bradley",
      rating: 4,
      isTarget: false,
      businessName: "Downtown Dental",
      competitorId: "c1",
      reviewText: "Same-day appointment and friendly front desk. Insurance questions were handled quickly.",
    }),
  ],
  keywordGaps: [],
  trendingKeywords: [],
  positivePct: 82,
  negativePct: 8,
  themeMovement: [],
  sentiment: {
    yours: {
      sentiment: {
        positive: 82,
        negative: 8,
        neutral: 10,
        total: 50,
        positivePct: 82,
        negativePct: 8,
        neutralPct: 10,
      },
      themes: [
        { themeId: "speed_scheduling", label: "Direction of use", reviewCount: 42, pct: 22 },
        { themeId: "pricing_value", label: "HVAC unit", reviewCount: 36, pct: 19 },
        { themeId: "service_quality", label: "Great service", reviewCount: 31, pct: 16 },
        { themeId: "hard_work", label: "Workmanship", reviewCount: 28, pct: 15 },
        { themeId: "staff_crew", label: "Staff member", reviewCount: 24, pct: 13 },
        { themeId: "communication", label: "Fair price", reviewCount: 21, pct: 11 },
        { themeId: "professionalism", label: "Professionalism", reviewCount: 18, pct: 9 },
        { themeId: "ease_convenience", label: "Quick response", reviewCount: 15, pct: 8 },
        { themeId: "reliability_trust", label: "Highly recommend", reviewCount: 12, pct: 6 },
        { themeId: "customer_service", label: "Customer service", reviewCount: 9, pct: 5 },
        { themeId: "overall_satisfaction", label: "Detailed estimate", reviewCount: 7, pct: 4 },
      ],
    },
    competitors: [
      {
        id: "c1",
        name: "Downtown Dental",
        reviewCount: 12,
        sentiment: {
          positive: 9,
          negative: 1,
          neutral: 2,
          total: 12,
          positivePct: 75,
          negativePct: 8,
          neutralPct: 17,
        },
        themes: [
          { themeId: "speed_scheduling", label: "Speed & Scheduling", reviewCount: 7, pct: 58 },
          { themeId: "pricing_value", label: "Pricing & Value", reviewCount: 4, pct: 33 },
        ],
      },
    ],
    entities: [
      {
        id: "target",
        label: "You",
        isTarget: true,
        reviewCount: 3,
        sentiment: {
          positive: 2,
          negative: 0,
          neutral: 1,
          total: 3,
          positivePct: 67,
          negativePct: 0,
          neutralPct: 33,
        },
        themes: [
          { themeId: "staff_crew", label: "Friendly Staff", reviewCount: 2, pct: 67 },
          { themeId: "service_quality", label: "Service Quality", reviewCount: 2, pct: 67 },
        ],
        themeDetails: [
          {
            themeId: "staff_crew",
            label: "Friendly Staff",
            reviewCount: 2,
            pct: 67,
            matchedPhrases: ["friendly", "professional"],
            reviews: [
              {
                id: "y1",
                reviewerName: "Sarah Mitchell",
                rating: 5,
                reviewDate: "2026-06-18",
                reviewText: "Great experience from start to finish. The team was professional, on time, and explained everything clearly.",
                businessName: "Bright Smile Dental",
                isTarget: true,
                matchedPhrases: ["professional", "friendly staff"],
              },
            ],
          },
        ],
      },
      {
        id: "c1",
        label: "Downtown Dental",
        isTarget: false,
        reviewCount: 2,
        sentiment: {
          positive: 2,
          negative: 0,
          neutral: 0,
          total: 2,
          positivePct: 100,
          negativePct: 0,
          neutralPct: 0,
        },
        themes: [
          { themeId: "speed_scheduling", label: "Speed & Scheduling", reviewCount: 2, pct: 100 },
        ],
        themeDetails: [
          {
            themeId: "speed_scheduling",
            label: "Speed & Scheduling",
            reviewCount: 2,
            pct: 100,
            matchedPhrases: ["same-day", "on time"],
            reviews: [
              {
                id: "cr3",
                reviewerName: "Tom Bradley",
                rating: 4,
                reviewDate: "2026-06-18",
                reviewText: "Same-day appointment and friendly front desk. Insurance questions were handled quickly.",
                businessName: "Downtown Dental",
                isTarget: false,
                matchedPhrases: ["same-day"],
              },
            ],
          },
        ],
      },
    ],
    marketSentiment: {
      positive: 74,
      negative: 12,
      neutral: 14,
      total: 120,
      positivePct: 74,
      negativePct: 12,
      neutralPct: 14,
    },
    themeComparison: [
      {
        themeId: "staff_crew",
        label: "Friendly Staff",
        yours: 2,
        yoursPct: 67,
        competitorAvg: 1,
        competitorAvgPct: 25,
        topCompetitor: "Downtown Dental",
        topCompetitorPct: 25,
      },
      {
        themeId: "speed_scheduling",
        label: "Speed & Scheduling",
        yours: 0,
        yoursPct: 0,
        competitorAvg: 2,
        competitorAvgPct: 67,
        topCompetitor: "Downtown Dental",
        topCompetitorPct: 67,
      },
      {
        themeId: "service_quality",
        label: "Service Quality",
        yours: 2,
        yoursPct: 67,
        competitorAvg: 1,
        competitorAvgPct: 33,
        topCompetitor: "Family Smiles",
        topCompetitorPct: 33,
      },
    ],
    themeMovement: [],
    entityMovement: [],
    insights: [
      {
        id: "i1",
        title: "You lead on service quality",
        description: "Customers mention quality and staff more often in your reviews than competitor averages.",
      },
      {
        id: "i2",
        title: "Speed is a competitor strength",
        description: "Downtown Dental earns more same-day and scheduling praise — worth matching operationally.",
      },
    ],
  },
  unanswered: [
    review("u1", {
      reviewerName: "Emily Nguyen",
      replied: false,
      daysWaiting: 5,
      urgency: "medium",
    }),
    review("u2", {
      reviewerName: "Amy Lewis",
      rating: 2,
      replied: false,
      daysWaiting: 9,
      urgency: "high",
    }),
  ],
  suggestions: [
    {
      id: "s1",
      title: "Reply to 2 unanswered reviews",
      description: "Improve response rate and show you care about feedback.",
      type: "reply",
    },
    {
      id: "s2",
      title: "Request reviews from recent patients",
      description: "You are 12 reviews behind the top 3 competitors.",
      type: "request",
    },
  ],
  syncState: { needsRun: false, message: null },
};
