import type { GrowthAuditSections } from "@/lib/growth-audit/types";

export const GROWTH_AUDIT_PREVIEW_BUSINESS_ID = "preview-growth-audit";

function check(
  id: string,
  label: string,
  status: "match" | "partial" | "missing" | "mismatch",
  bucket: "relevance" | "distance" | "prominence" | "trust",
  gbpValue?: string,
  websiteValue?: string
) {
  return { id, label, status, bucket, gbpValue, websiteValue, whyItMatters: `${label} affects local visibility.` };
}

function task(
  title: string,
  sourceSection: string,
  priority: "high" | "medium" | "low",
  difficulty: "easy" | "medium" | "hard",
  impactStars: number,
  timeframe: "urgent" | "7-day" | "30-day",
  timeEstimate: string
) {
  return {
    title,
    description: `Complete: ${title.toLowerCase()}.`,
    why: "Closes a ranking gap competitors already cover.",
    impact: priority === "high" ? ("high" as const) : priority === "medium" ? ("medium" as const) : ("low" as const),
    effort: difficulty === "easy" ? ("low" as const) : difficulty === "medium" ? ("medium" as const) : ("high" as const),
    bucket: "prominence" as const,
    timeframe,
    module: sourceSection,
    priority,
    impactStars,
    difficulty,
    timeEstimate,
    sourceSection,
  };
}

const tasks = [
  task("Add hours to GBP profile", "gbp", "high", "easy", 5, "urgent", "15 min"),
  task("Publish 8 recent work photos", "gbp", "high", "easy", 4, "urgent", "30 min"),
  task("Create Woodbridge junk removal service page", "service-coverage", "high", "medium", 5, "7-day", "2–3 hours"),
  task("Fix NAP mismatch on website footer", "website", "high", "easy", 4, "urgent", "20 min"),
  task("Add Dale City neighborhood page", "local-coverage", "medium", "medium", 3, "7-day", "1–2 hours"),
  task("Request 10 reviews this week", "competitor-gap", "high", "easy", 5, "7-day", "45 min"),
  task("Add Garage Cleanout secondary category", "gbp", "medium", "easy", 3, "30-day", "10 min"),
  task("Build Manassas city page with map embed", "local-coverage", "medium", "hard", 4, "30-day", "3–4 hours"),
  task("Match H1 titles to GBP services", "website", "medium", "medium", 3, "30-day", "1 hour"),
  task("Close backlink gap on 5 directories", "competitor-gap", "low", "hard", 2, "30-day", "4 hours"),
];

export const growthAuditPreviewSections: GrowthAuditSections = {
  overview: {
    growthScore: 72,
    strengths: [
      "Primary category and NAP basics are present",
      "Review rating stays above 4.7",
      "Core service keywords appear on homepage",
    ],
    weaknesses: [
      "Hours missing on GBP",
      "Thin local page coverage vs top competitors",
      "Service pages missing for 3 GBP services",
    ],
    immediateFixes: [
      "Add business hours today",
      "Upload job-site photos",
      "Publish Woodbridge service page",
    ],
    aiSummary:
      "Premier Junk Removal is competitive on trust and relevance, but Maps growth is capped by incomplete GBP engagement and thin local/service page coverage. Closing hours, photos, and three missing service pages is the fastest path to a higher growth score.",
    scanScores: {
      relevance: 78,
      distance: 71,
      prominence: 64,
      trust: 82,
      overall: 74,
    },
    hasScan: true,
  },
  gbp: {
    score: 68,
    profile: {
      name: "Premier Junk Removal",
      address: "14500 Jefferson Davis Hwy, Woodbridge, VA 22191",
      phone: "(703) 555-0142",
      website: "https://premierjunkremoval.example",
      primaryCategory: "Junk removal service",
      secondaryCategories: ["Hauling service"],
      services: ["Junk Removal", "Furniture Removal", "Garage Cleanout", "Estate Cleanout"],
      city: "Woodbridge",
      state: "VA",
      rating: 4.8,
      reviewCount: 186,
      photoCount: 24,
      postCount: 2,
      hoursText: null,
      description: "Same-day junk removal across Prince William County.",
    },
    checks: [
      check("name", "Business name", "match", "relevance", "Premier Junk Removal", "Premier Junk Removal"),
      check("address", "Address", "match", "distance", "14500 Jefferson Davis Hwy", "14500 Jefferson Davis Hwy"),
      check("phone", "Phone", "partial", "trust", "(703) 555-0142", "(703) 555-0199"),
      check("hours", "Hours", "missing", "prominence"),
      check("category", "Primary category", "match", "relevance", "Junk removal service", "Junk removal"),
      check("photos", "Photos", "partial", "prominence", "24 photos", "Gallery present"),
      check("posts", "GBP posts", "partial", "prominence", "2 posts", "—"),
      check("description", "Description", "match", "relevance", "Same-day junk removal…", "Same-day junk removal…"),
    ],
    reviews: {
      rating: 4.8,
      reviewCount: 186,
      recentReviewCount: 14,
      keywords: ["professional", "same day", "clean", "friendly"],
      missingThemes: ["pricing", "recycling"],
      recommendations: ["Ask happy customers to mention same-day service"],
      sampleReviews: [
        { text: "Crew was fast and professional.", rating: 5, date: "2026-07-01" },
        { text: "Same-day pickup saved us.", rating: 5, date: "2026-06-22" },
      ],
      velocityAvailable: true,
      velocityWarning: null,
      warnings: [],
    },
    posts: {
      postCount: 2,
      recentPosts: [
        { title: "Spring cleanout special", snippet: "Book same-day garage cleanouts.", date: "2026-05-12" },
      ],
      recommendedTopics: ["Before/after jobs", "Recycling tips", "HOA partnerships"],
    },
    photos: {
      photoCount: 24,
      competitorAvg: 48,
      recommendations: ["Add exterior truck branding shots", "Upload team-at-work photos"],
    },
    categoryAlignment: {
      currentPrimary: "Junk removal service",
      currentSecondary: ["Hauling service"],
      patterns: [],
      recommendations: [
        {
          category: "Garage cleaning service",
          onYourGbp: false,
          isYourPrimary: false,
          top3Count: 2,
          top10Count: 6,
          top20Count: 11,
          totalCompetitors: 20,
          confidence: "medium",
          recommendation: "consider_secondary",
          recommendationText: "Consider if accurate",
          notes: "Appears often among top local junk competitors.",
        },
      ],
      reviewIdeas: [],
      avoid: [],
      disclaimer: "Only add accurate categories.",
      competitorCount: 20,
    },
  },
  website: {
    score: 74,
    checks: [
      check("nap", "NAP consistency", "partial", "trust", "Premier Junk Removal", "Phone mismatch"),
      check("services", "Service pages", "partial", "relevance", "4 services", "2 pages found"),
      check("cta", "Click-to-call", "match", "prominence", "Present", "Present"),
      check("hours-web", "Hours on site", "missing", "prominence"),
      check("local-pages", "Local pages", "partial", "distance", "1 city page", "Competitors avg 4"),
      check("schema", "LocalBusiness schema", "missing", "trust"),
    ],
  },
  serviceCoverage: {
    score: 61,
    rows: [
      {
        service: "Junk Removal",
        gbpListed: true,
        pageExists: true,
        pageUrl: "https://premierjunkremoval.example/junk-removal",
        score: 82,
        status: "excellent",
        onYourGbp: true,
        competitorTop20Count: 18,
        opportunity: "low",
      },
      {
        service: "Furniture Removal",
        gbpListed: true,
        pageExists: true,
        pageUrl: "https://premierjunkremoval.example/furniture-removal",
        score: 70,
        status: "weak",
        onYourGbp: true,
        competitorTop20Count: 14,
        opportunity: "medium",
      },
      {
        service: "Garage Cleanout",
        gbpListed: true,
        pageExists: false,
        score: 20,
        status: "missing",
        onYourGbp: true,
        competitorTop20Count: 12,
        opportunity: "high",
      },
      {
        service: "Estate Cleanout",
        gbpListed: true,
        pageExists: false,
        score: 18,
        status: "missing",
        onYourGbp: true,
        competitorTop20Count: 9,
        opportunity: "high",
      },
      {
        service: "Appliance Removal",
        gbpListed: false,
        pageExists: false,
        score: 10,
        status: "missing",
        onYourGbp: false,
        competitorTop20Count: 11,
        opportunity: "medium",
      },
    ],
    categoryGap: {
      primaryCategory: "Junk removal service",
      secondaryCategories: ["Hauling service"],
      competitorCategories: ["Garage cleaning service", "Waste management service"],
      missingOpportunities: ["Garage cleaning service"],
      services: ["Junk Removal", "Furniture Removal", "Garage Cleanout", "Estate Cleanout"],
      missingPages: [
        { service: "Garage Cleanout", suggestedTitle: "Garage Cleanout in Woodbridge, VA", reason: "No matching page" },
        { service: "Estate Cleanout", suggestedTitle: "Estate Cleanout Woodbridge", reason: "No matching page" },
      ],
    },
    core30: {
      completionScore: 58,
      gbpServicesFound: 4,
      matchingPagesFound: 2,
      missingPages: [
        { name: "Garage Cleanout", suggestedTitle: "Garage Cleanout Woodbridge VA" },
        { name: "Estate Cleanout", suggestedTitle: "Estate Cleanout near Woodbridge" },
      ],
      weakPages: [{ url: "/furniture-removal", issue: "Thin copy under 400 words" }],
      wrongTitlePages: [],
      servicePageCount: 2,
      locationPageCount: 1,
    },
    serviceKeywords: {
      totalCompetitors: 20,
      rows: [
        {
          service: "garage cleanout",
          onYourWebsite: false,
          onYourGbp: true,
          competitorTop3Count: 2,
          competitorTop10Count: 7,
          competitorTop20Count: 12,
          totalCompetitors: 20,
          opportunity: "high",
          note: "High competitor coverage; missing page.",
        },
        {
          service: "estate cleanout",
          onYourWebsite: false,
          onYourGbp: true,
          competitorTop3Count: 1,
          competitorTop10Count: 5,
          competitorTop20Count: 9,
          totalCompetitors: 20,
          opportunity: "high",
          note: "Opportunity to publish dedicated page.",
        },
        {
          service: "furniture removal",
          onYourWebsite: true,
          onYourGbp: true,
          competitorTop3Count: 3,
          competitorTop10Count: 8,
          competitorTop20Count: 14,
          totalCompetitors: 20,
          opportunity: "medium",
          note: "Present but thin vs competitors.",
        },
      ],
    },
  },
  localCoverage: {
    score: 58,
    neighborhoods: [
      {
        area: "Lake Ridge",
        type: "neighborhood",
        hasPage: false,
        mentionedOnSite: true,
        competitorCount: 7,
        opportunity: "high",
        status: "missing",
      },
      {
        area: "Dale City",
        type: "neighborhood",
        hasPage: false,
        mentionedOnSite: false,
        competitorCount: 6,
        opportunity: "high",
        status: "missing",
      },
      {
        area: "Occoquan",
        type: "neighborhood",
        hasPage: true,
        mentionedOnSite: true,
        competitorCount: 3,
        opportunity: "low",
        status: "excellent",
      },
    ],
    cities: [
      {
        area: "Woodbridge",
        type: "city",
        hasPage: true,
        mentionedOnSite: true,
        competitorCount: 12,
        opportunity: "low",
        status: "excellent",
      },
      {
        area: "Manassas",
        type: "city",
        hasPage: false,
        mentionedOnSite: false,
        competitorCount: 9,
        opportunity: "medium",
        status: "missing",
      },
    ],
    opportunities: [],
  },
  competitorGap: {
    score: 66,
    result: {
      competitors: [
        {
          name: "Junk King Woodbridge",
          rank: 1,
          categories: ["Junk removal service"],
          rating: 4.7,
          reviewCount: 312,
          photoCount: 64,
          postCount: 12,
          reviewKeywords: ["fast", "professional"],
          servicePageCount: 8,
          localPageCount: 5,
        },
        {
          name: "College Hunks Hauling Junk",
          rank: 2,
          categories: ["Junk removal service", "Hauling service"],
          rating: 4.6,
          reviewCount: 248,
          photoCount: 51,
          postCount: 9,
          reviewKeywords: ["friendly", "on time"],
          servicePageCount: 7,
          localPageCount: 4,
        },
        {
          name: "LoadUp Local",
          rank: 3,
          categories: ["Junk removal service"],
          rating: 4.5,
          reviewCount: 190,
          photoCount: 40,
          postCount: 4,
          reviewKeywords: ["easy", "quote"],
          servicePageCount: 5,
          localPageCount: 3,
        },
      ],
      whyTheyBeatYou: [
        "Higher review velocity and photo volume",
        "More dedicated service and neighborhood pages",
        "More consistent GBP posting cadence",
      ],
      yourGaps: [
        "186 reviews vs top-3 average ~250",
        "Missing garage/estate service pages",
        "Hours absent on GBP",
      ],
      metrics: {
        reviews: { you: 186, top3Avg: 250, top20Avg: 160 },
        servicePages: { you: 2, top3Avg: 7 },
        localPages: { you: 1, top3Avg: 4 },
        categories: { you: 2, top3Avg: 3 },
        referringDomains: { you: 28, competitorTotal: 74 },
      },
      competitorCount: 20,
      backlinkGap: null,
    },
  },
  growthPlan: {
    tasks,
    urgent: tasks.filter((t) => t.timeframe === "urgent"),
    sevenDay: tasks.filter((t) => t.timeframe === "7-day"),
    thirtyDay: tasks.filter((t) => t.timeframe === "30-day"),
  },
};

export const growthAuditPreviewApi = {
  run: {
    id: "run-preview-growth-audit",
    status: "complete",
    growthScore: growthAuditPreviewSections.overview.growthScore,
    sections: growthAuditPreviewSections,
    growthPlan: growthAuditPreviewSections.growthPlan.tasks,
    extended: {
      citations: { auditId: "cit-1", status: "complete", score: 71 },
      reputation: { auditId: "rep-1", status: "complete", score: 78 },
      keywords: { summary: { tracked: 24 }, status: "complete" },
      backlinkGap: { runId: "bg-1", status: "complete", summary: null },
    },
    progressStage: null,
    errorMessage: null,
    startedAt: new Date().toISOString(),
    finishedAt: new Date().toISOString(),
  },
};

export const growthAuditPreviewMomentum = {
  run: {
    metrics_json: {
      marketReviews30d: 96,
      weeklyBuckets8to30: [
        { label: "W1", count: 3 },
        { label: "W2", count: 4 },
        { label: "W3", count: 2 },
        { label: "W4", count: 5 },
        { label: "W5", count: 4 },
        { label: "W6", count: 6 },
        { label: "W7", count: 5 },
        { label: "W8", count: 7 },
      ],
    },
  },
};
