import PDFDocument from "pdfkit";
import type { CompetitorLimit } from "@/lib/reporting/pdf/constants";
import { gridPointSpacingMeters } from "@/lib/reporting/pdf/mercator";
import type { ReportCompetitorRow, SingleScanReportPayload } from "@/lib/reporting/types";

function fmt(n: number | null | undefined, digits = 1): string {
  if (n == null || Number.isNaN(n)) return "—";
  return Number(n).toFixed(digits);
}

function pct(n: number | null | undefined): string {
  if (n == null || Number.isNaN(n)) return "—";
  return `${Math.round(n)}%`;
}

function selectCompetitors(
  rows: ReportCompetitorRow[],
  limit: CompetitorLimit
): ReportCompetitorRow[] {
  const target = rows.find((r) => r.isTarget);
  const others = rows
    .filter((r) => !r.isTarget)
    .slice()
    .sort((a, b) => (b.solv ?? 0) - (a.solv ?? 0) || (a.arp ?? 99) - (b.arp ?? 99));
  const capped =
    limit === "all" ? others : others.slice(0, typeof limit === "number" ? limit : 20);
  return target ? [target, ...capped] : capped;
}

function drawHeader(
  doc: PDFKit.PDFDocument,
  payload: SingleScanReportPayload,
  pageLabel: string
) {
  const accent = payload.whiteLabel.accentColor || "#059669";
  const company = payload.whiteLabel.companyName || "Local SEO Express";
  doc.save();
  doc.rect(0, 0, doc.page.width, 36).fill(accent);
  doc.fillColor("#ffffff").fontSize(10).font("Helvetica-Bold");
  doc.text(company, 36, 12, { width: doc.page.width - 160, continued: false });
  doc.font("Helvetica").fontSize(9);
  doc.text(pageLabel, 36, 12, { align: "right", width: doc.page.width - 72 });
  doc.restore();
}

function drawFooter(
  doc: PDFKit.PDFDocument,
  payload: SingleScanReportPayload,
  reportId: string,
  pageNum: number,
  pageCount: number
) {
  const y = doc.page.height - 40;
  doc.save();
  doc.moveTo(36, y).lineTo(doc.page.width - 36, y).strokeColor("#e4e4e7").lineWidth(0.5).stroke();
  doc.fillColor("#71717a").fontSize(8).font("Helvetica");
  const left = payload.whiteLabel.hidePlatformBranding
    ? payload.business.name
    : `Generated by Maps Growth Agent · ${payload.business.name}`;
  const generated = new Date(payload.generatedAt).toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  });
  doc.text(`${left} · Report ${reportId.slice(0, 8)} · ${generated}`, 36, y + 8, {
    width: doc.page.width - 120,
  });
  doc.text(`Page ${pageNum} of ${pageCount}`, 36, y + 8, {
    align: "right",
    width: doc.page.width - 72,
  });
  if (payload.whiteLabel.footerText) {
    doc.text(payload.whiteLabel.footerText, 36, y + 20, {
      width: doc.page.width - 72,
      align: "center",
    });
  }
  doc.restore();
}

function kpiBox(
  doc: PDFKit.PDFDocument,
  x: number,
  y: number,
  w: number,
  h: number,
  label: string,
  value: string
) {
  doc.save();
  doc.roundedRect(x, y, w, h, 6).fillAndStroke("#fafafa", "#e4e4e7");
  doc.fillColor("#71717a").fontSize(8).font("Helvetica").text(label, x + 8, y + 8, { width: w - 16 });
  doc.fillColor("#18181b").fontSize(14).font("Helvetica-Bold").text(value, x + 8, y + 22, {
    width: w - 16,
  });
  doc.restore();
}

export async function renderSingleScanPdf(params: {
  payload: SingleScanReportPayload;
  mapPng: Buffer;
  heatmapPng?: Buffer | null;
  reportId: string;
  competitorLimit?: CompetitorLimit;
  centerLat: number;
  centerLng: number;
}): Promise<Buffer> {
  const payload = params.payload;
  const competitorLimit = params.competitorLimit ?? 20;
  const competitors = selectCompetitors(payload.competitors, competitorLimit);
  const spacing = Math.round(
    gridPointSpacingMeters(payload.parameters.gridSize, payload.parameters.radiusMeters)
  );

  // Estimate pages: 3 fixed + competitor pages
  const rowsPerPage = 18;
  const competitorPages = Math.max(1, Math.ceil(competitors.length / rowsPerPage));
  const pageCount = 3 + competitorPages;

  const doc = new PDFDocument({
    size: "LETTER",
    margins: { top: 48, bottom: 52, left: 36, right: 36 },
    info: {
      Title: `Local Rank Scan Report — ${payload.business.name}`,
      Author: payload.whiteLabel.companyName || "Local SEO Express",
      Subject: payload.parameters.keyword,
    },
  });

  const chunks: Buffer[] = [];
  doc.on("data", (c) => chunks.push(c as Buffer));

  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  let pageNum = 1;

  // ── Page 1: Overview ─────────────────────────────────────────────
  drawHeader(doc, payload, "Local Rank Scan Report");
  doc.moveDown(1.2);
  doc.fillColor("#18181b").fontSize(20).font("Helvetica-Bold").text("Local Rank Scan Report");
  doc.moveDown(0.35);
  doc.fontSize(12).font("Helvetica").fillColor("#3f3f46");
  doc.text(payload.business.name);
  if (payload.business.address) doc.text(payload.business.address);
  doc.moveDown(0.5);

  const metaLeft = [
    ["Keyword", payload.parameters.keyword],
    ["Search provider", "Google Maps"],
    ["Scan date", new Date(payload.parameters.scannedAt).toLocaleString("en-US")],
    ["Grid size", `${payload.parameters.gridSize}×${payload.parameters.gridSize}`],
  ] as const;
  const metaRight = [
    ["Radius", `${Math.round(payload.parameters.radiusMeters)} m`],
    ["Pin spacing", `${spacing} m`],
    ["Center", `${params.centerLat.toFixed(5)}, ${params.centerLng.toFixed(5)}`],
    ["Scan ID", payload.parameters.scanId.slice(0, 8)],
  ] as const;

  const metaY = doc.y;
  doc.fontSize(9).fillColor("#52525b");
  metaLeft.forEach((row, i) => {
    doc.font("Helvetica-Bold").text(`${row[0]}: `, 36, metaY + i * 14, { continued: true });
    doc.font("Helvetica").text(row[1]);
  });
  metaRight.forEach((row, i) => {
    doc.font("Helvetica-Bold").text(`${row[0]}: `, 320, metaY + i * 14, { continued: true });
    doc.font("Helvetica").text(row[1]);
  });
  doc.y = metaY + metaLeft.length * 14 + 16;

  const k = payload.kpis;
  const boxes: Array<[string, string]> = [
    ["ARP", fmt(k.arp)],
    ["ATRP", fmt(k.atrp)],
    ["SoLV", pct(k.solv)],
    ["Top 3", pct(k.top3Pct)],
    ["Top 10", pct(k.top10Pct)],
    ["Visibility", pct(k.visibilityScore)],
    ["Best rank", k.bestRank != null ? String(k.bestRank) : "—"],
    ["Worst rank", k.worstRank != null ? String(k.worstRank) : "—"],
  ];
  const boxW = 120;
  const boxH = 48;
  const gap = 10;
  let bx = 36;
  let by = doc.y;
  boxes.forEach((b, i) => {
    if (i > 0 && i % 4 === 0) {
      bx = 36;
      by += boxH + gap;
    }
    kpiBox(doc, bx, by, boxW, boxH, b[0], b[1]);
    bx += boxW + gap;
  });
  doc.y = by + boxH + 20;

  doc.fillColor("#18181b").fontSize(11).font("Helvetica-Bold").text("Coverage snapshot");
  doc.moveDown(0.3);
  doc.font("Helvetica").fontSize(10).fillColor("#3f3f46");
  doc.text(
    `Found in ${k.foundCells} of ${k.totalCells} cells · Top 3 in ${Math.round((k.top3Pct / 100) * k.totalCells)} cells · Top 10 in ${Math.round((k.top10Pct / 100) * k.totalCells)} cells · Not found in ${Math.round((k.notFoundPct / 100) * k.totalCells)} cells`
  );

  drawFooter(doc, payload, params.reportId, pageNum, pageCount);

  // ── Page 2: Map ──────────────────────────────────────────────────
  doc.addPage();
  pageNum++;
  drawHeader(doc, payload, "Rank grid map");
  doc.moveDown(1);
  doc.fillColor("#18181b").fontSize(16).font("Helvetica-Bold").text("Full rank-grid map");
  doc.moveDown(0.3);
  doc.fontSize(9).font("Helvetica").fillColor("#52525b");
  doc.text(
    `${payload.parameters.gridSize}×${payload.parameters.gridSize} · ${Math.round(payload.parameters.radiusMeters)} m radius · ~${spacing} m between pins`
  );
  doc.moveDown(0.4);
  const mapMaxW = doc.page.width - 72;
  const mapMaxH = doc.page.height - 160;
  doc.image(params.mapPng, 36, doc.y, {
    fit: [mapMaxW, mapMaxH],
    align: "center",
  });
  drawFooter(doc, payload, params.reportId, pageNum, pageCount);

  // ── Page 3: Performance ──────────────────────────────────────────
  doc.addPage();
  pageNum++;
  drawHeader(doc, payload, "Performance breakdown");
  doc.moveDown(1);
  doc.fillColor("#18181b").fontSize(16).font("Helvetica-Bold").text("Performance breakdown");
  doc.moveDown(0.5);

  doc.fontSize(11).font("Helvetica-Bold").text("Rank distribution");
  doc.moveDown(0.3);
  const maxBucket = Math.max(1, ...payload.rankDistribution.map((d) => d.count));
  const barX = 36;
  let barY = doc.y;
  for (const bucket of payload.rankDistribution) {
    const barW = ((doc.page.width - 200) * bucket.count) / maxBucket;
    doc.font("Helvetica").fontSize(9).fillColor("#3f3f46");
    doc.text(bucket.label, barX, barY, { width: 90 });
    doc.roundedRect(barX + 100, barY, Math.max(4, barW), 12, 3).fill("#059669");
    doc.fillColor("#18181b").text(String(bucket.count), barX + 110 + barW, barY);
    barY += 20;
  }
  doc.y = barY + 12;

  if (params.heatmapPng) {
    doc.fontSize(11).font("Helvetica-Bold").fillColor("#18181b").text("Heatmap snapshot");
    doc.moveDown(0.3);
    doc.image(params.heatmapPng, 36, doc.y, {
      fit: [280, 280],
    });
    doc.y += 12;
  }

  doc.moveDown(0.5);
  doc.fontSize(11).font("Helvetica-Bold").fillColor("#18181b").text("Metric definitions");
  doc.moveDown(0.25);
  doc.fontSize(9).font("Helvetica").fillColor("#3f3f46");
  const defs = [
    "ARP — Average rank of cells where the business appears in the top 20.",
    "ATRP — Average total rank treating not-found cells as rank 21.",
    "SoLV — Share of local voice: percent of cells ranking in the top 3.",
    "Visibility — Percent of cells ranking in the top 10.",
  ];
  for (const line of defs) doc.text(`• ${line}`);
  doc.moveDown(0.5);

  const leader = payload.competitors
    .filter((c) => !c.isTarget)
    .slice()
    .sort((a, b) => b.solv - a.solv)[0];
  const you = payload.competitors.find((c) => c.isTarget);
  doc.fontSize(11).font("Helvetica-Bold").fillColor("#18181b").text("Market comparison");
  doc.moveDown(0.25);
  doc.fontSize(9).font("Helvetica").fillColor("#3f3f46");
  doc.text(`Your SoLV: ${pct(you?.solv ?? k.solv)}`);
  if (leader) {
    doc.text(`Market-leading SoLV: ${pct(leader.solv)} (${leader.name})`);
    doc.text(`Gap to leader: ${fmt((leader.solv ?? 0) - (you?.solv ?? k.solv), 0)} pts`);
  }
  doc.text(`Active competitors in report: ${Math.max(0, competitors.length - (you ? 1 : 0))}`);
  doc.text(`Average target rank (ARP): ${fmt(k.arp)}`);

  drawFooter(doc, payload, params.reportId, pageNum, pageCount);

  // ── Competitor pages ─────────────────────────────────────────────
  const colX = [36, 56, 200, 340, 380, 430, 470, 510];
  const headers = ["#", "Business", "Address", "Rating", "Reviews", "Found", "SoLV", "ARP"];

  for (let p = 0; p < competitorPages; p++) {
    doc.addPage();
    pageNum++;
    drawHeader(doc, payload, "Competitor comparison");
    doc.moveDown(1);
    doc.fillColor("#18181b").fontSize(14).font("Helvetica-Bold").text("Competitor comparison");
    doc.moveDown(0.2);
    doc.fontSize(8).font("Helvetica").fillColor("#71717a");
    doc.text(
      `Sorted by SoLV (desc) · Showing ${competitorLimit === "all" ? "all" : `top ${competitorLimit}`} competitors · Target row highlighted`
    );
    doc.moveDown(0.4);

    const slice = competitors.slice(p * rowsPerPage, (p + 1) * rowsPerPage);
    let y = doc.y;
    doc.font("Helvetica-Bold").fontSize(8).fillColor("#3f3f46");
    headers.forEach((h, i) => doc.text(h, colX[i], y, { width: i === 1 || i === 2 ? 130 : 40 }));
    y += 14;
    doc
      .moveTo(36, y)
      .lineTo(doc.page.width - 36, y)
      .strokeColor("#e4e4e7")
      .stroke();
    y += 6;

    slice.forEach((row, idx) => {
      const absolute = p * rowsPerPage + idx + 1;
      if (row.isTarget) {
        doc.rect(36, y - 2, doc.page.width - 72, 16).fill("#ecfdf5");
      }
      doc.fillColor("#18181b").font("Helvetica").fontSize(8);
      const vals = [
        String(absolute),
        (row.isTarget ? "★ " : "") + row.name.slice(0, 28),
        (row.address ?? "—").slice(0, 22),
        row.rating != null ? fmt(row.rating) : "—",
        row.reviewCount != null ? String(row.reviewCount) : "—",
        `${Math.round((row.appearancePct / 100) * row.totalCells)}`,
        pct(row.solv),
        fmt(row.arp),
      ];
      vals.forEach((v, i) =>
        doc.text(v, colX[i], y, { width: i === 1 || i === 2 ? 130 : 40 })
      );
      y += 16;
    });

    drawFooter(doc, payload, params.reportId, pageNum, pageCount);
  }

  doc.end();
  return done;
}
