import type { ReputationAlertsData } from "@/lib/reputation/alerts-data";
import type { ReputationModulesAuditData } from "@/lib/reputation/reputation-modules-audit";

export const REPUTATION_PREVIEW_BUSINESS_ID = "preview-reputation-intelligence";
export const REPUTATION_PREVIEW_BUSINESS_NAME = "A-Team Junk Removal";

export type ReputationTemplateRow = {
  id: string;
  channel: "sms" | "email" | "sequence";
  name: string;
  subject?: string | null;
  body: string;
  snippet: string;
  type: string;
  lastUpdated: string;
  createdAt?: string;
  usageCount: number;
  conversionPct: number | null;
  isDefault?: boolean;
  status?: "active" | "archived";
  source?: "business" | "industry";
  steps?: number;
  recommendedTiming?: string;
  mergeFields?: string[];
};

export type ReputationTemplatePreviewKpis = {
  sms: number;
  email: number;
  sequences: number;
  industry: number;
  mine: number;
};

export const reputationTemplatesPreviewKpis: ReputationTemplatePreviewKpis = {
  sms: 18,
  email: 14,
  sequences: 6,
  industry: 24,
  mine: 12,
};

export const reputationTemplatesPreviewData: ReputationTemplateRow[] = [
  {
    id: "tpl-friendly-short-sweet",
    channel: "sms",
    name: "Friendly – Short & Sweet",
    body: "Hi {{first_name}}, thanks for choosing {{business_name}}! A quick review means the world to us: {{review_link}} Reply STOP to opt out.",
    snippet: "Hi {{first_name}}, thanks for choosing {{business_name}}! A quick review means the world to us...",
    type: "Single Message",
    lastUpdated: "2025-05-08T00:00:00.000Z",
    createdAt: "2025-04-01T00:00:00.000Z",
    usageCount: 128,
    conversionPct: 7.4,
    isDefault: true,
    status: "active",
    source: "business",
    recommendedTiming: "Send 1–2 days after service",
    mergeFields: ["first_name", "business_name", "review_link"],
  },
  {
    id: "tpl-post-service-followup",
    channel: "sms",
    name: "Post-Service Follow-Up",
    body: "Hi {{first_name}}, it was great serving you! Could you take 60 seconds to share your experience? {{review_link}} Reply STOP to opt out.",
    snippet: "Hi {{first_name}}, it was great serving you! Could you take 60 seconds...",
    type: "Single Message",
    lastUpdated: "2025-05-05T00:00:00.000Z",
    createdAt: "2025-03-15T00:00:00.000Z",
    usageCount: 342,
    conversionPct: 12.1,
    status: "active",
    source: "business",
    recommendedTiming: "Send same day as service",
    mergeFields: ["first_name", "review_link"],
  },
  {
    id: "tpl-email-after-job",
    channel: "email",
    name: "After-Job Thank You",
    subject: "How did we do, {{first_name}}?",
    body: "Hi {{first_name}},\n\nThank you for trusting {{business_name}} with your project. Your feedback helps neighbors choose confidently.\n\n{{review_link}}\n\nThanks again,\n{{business_name}} Team",
    snippet: "Thank you for trusting {{business_name}} with your project. Your feedback helps neighbors...",
    type: "Single Message",
    lastUpdated: "2025-04-30T00:00:00.000Z",
    createdAt: "2025-03-01T00:00:00.000Z",
    usageCount: 218,
    conversionPct: 9.8,
    status: "active",
    source: "business",
    recommendedTiming: "Send 2–3 days after service",
    mergeFields: ["first_name", "business_name", "review_link"],
  },
  {
    id: "tpl-email-30day",
    channel: "email",
    name: "30-Day Follow-Up Email",
    subject: "Still thinking about your recent service?",
    body: "Hi {{first_name}},\n\nWe hope you've been enjoying your clean space! If you have a moment, we'd love a quick review:\n{{review_link}}\n\nBest,\n{{business_name}}",
    snippet: "We hope you've been enjoying your clean space! If you have a moment...",
    type: "Single Message",
    lastUpdated: "2025-04-22T00:00:00.000Z",
    createdAt: "2025-02-20T00:00:00.000Z",
    usageCount: 87,
    conversionPct: 6.2,
    status: "active",
    source: "business",
    recommendedTiming: "Send 30 days after service",
    mergeFields: ["first_name", "business_name", "review_link"],
  },
  {
    id: "tpl-2step-sequence",
    channel: "sequence",
    name: "2-Step Review Sequence",
    body: "SMS day 1 → Email day 4 for completed jobs without a review.",
    snippet: "SMS day 1 → Email day 4 for completed jobs without a review.",
    type: "Sequence",
    lastUpdated: "2025-04-18T00:00:00.000Z",
    createdAt: "2025-02-10T00:00:00.000Z",
    usageCount: 156,
    conversionPct: 18.3,
    status: "active",
    source: "business",
    steps: 2,
  },
  {
    id: "tpl-industry-junk-removal",
    channel: "sms",
    name: "Junk Removal Starter",
    body: "Hi {{first_name}}, thanks for letting {{business_name}} clear the space! Could you leave a quick Google review? {{review_link}}",
    snippet: "Thanks for letting {{business_name}} clear the space! Could you leave a quick Google review...",
    type: "Industry Starter",
    lastUpdated: "2025-04-10T00:00:00.000Z",
    createdAt: "2025-01-15T00:00:00.000Z",
    usageCount: 64,
    conversionPct: 5.8,
    status: "active",
    source: "industry",
    recommendedTiming: "Send within 24 hours of pickup",
    mergeFields: ["first_name", "business_name", "review_link"],
  },
  {
    id: "tpl-vip-customer",
    channel: "sms",
    name: "VIP Customer Thank You",
    body: "Hi {{first_name}}, as one of our valued customers your opinion really matters. Would you share your experience? {{review_link}} Reply STOP to opt out.",
    snippet: "As one of our valued customers your opinion really matters. Would you share your experience...",
    type: "Single Message",
    lastUpdated: "2025-04-05T00:00:00.000Z",
    createdAt: "2025-01-10T00:00:00.000Z",
    usageCount: 38,
    conversionPct: 11.5,
    status: "active",
    source: "business",
    recommendedTiming: "Send 1 day after service",
    mergeFields: ["first_name", "review_link"],
  },
  {
    id: "tpl-legacy-review-ask",
    channel: "email",
    name: "Legacy Review Ask",
    subject: "Review request",
    body: "Please leave us a review: {{review_link}}",
    snippet: "Please leave us a review: {{review_link}}",
    type: "Single Message",
    lastUpdated: "2025-03-14T00:00:00.000Z",
    createdAt: "2024-11-01T00:00:00.000Z",
    usageCount: 74,
    conversionPct: 4.2,
    status: "archived",
    source: "business",
  },
];

export type ReputationContactPreviewRow = {
  id: string;
  customer_name: string | null;
  first_name: string | null;
  last_name: string | null;
  phone_e164: string | null;
  email_normalized: string | null;
  sms_opt_out: boolean;
  email_unsubscribed: boolean;
  tags: string[];
  source?: string | null;
  last_contacted_at?: string | null;
  campaign_attempts?: number | null;
  latest_reply_at?: string | null;
  review_completion?: unknown;
  created_at?: string;
  updated_at: string;
  last_service_at?: string | null;
  campaign_status?: string;
};

export type ReputationContactPreviewKpis = {
  all: number;
  eligible: number;
  requested: number;
  received: number;
  optedOut: number;
};

export const REPUTATION_CONTACTS_PREVIEW_TOTAL = 1248;

export const reputationContactsPreviewKpis: ReputationContactPreviewKpis = {
  all: 1248,
  eligible: 642,
  requested: 358,
  received: 132,
  optedOut: 116,
};

export const reputationContactsPreviewData: ReputationContactPreviewRow[] = [
  {
    id: "contact-1",
    customer_name: "James Harrington",
    first_name: "James",
    last_name: "Harrington",
    phone_e164: "+15715550142",
    email_normalized: "james.harrington@example.com",
    sms_opt_out: false,
    email_unsubscribed: false,
    tags: ["vip", "reviewed", "google"],
    source: "Housecall Pro",
    last_contacted_at: "2025-06-02T16:15:00.000Z",
    campaign_attempts: 2,
    review_completion: { rating: 5 },
    updated_at: "2025-06-02T16:15:00.000Z",
    last_service_at: "2025-05-31T10:00:00.000Z",
    campaign_status: "Post-Service Follow-Up Step 3 of 3",
  },
  {
    id: "contact-2",
    customer_name: "Maria Santos",
    first_name: "Maria",
    last_name: "Santos",
    phone_e164: "+15715550219",
    email_normalized: "maria.santos@example.com",
    sms_opt_out: false,
    email_unsubscribed: false,
    tags: ["eligible", "repeat"],
    source: "Housecall Pro",
    last_contacted_at: "2025-06-01T12:30:00.000Z",
    campaign_attempts: 1,
    updated_at: "2025-06-01T12:30:00.000Z",
    last_service_at: "2025-05-30T09:00:00.000Z",
    campaign_status: "Post-Service Follow-Up Step 2 of 3",
  },
  {
    id: "contact-3",
    customer_name: "Derek Johnson",
    first_name: "Derek",
    last_name: "Johnson",
    phone_e164: "+15715550387",
    email_normalized: "derek.johnson@example.com",
    sms_opt_out: false,
    email_unsubscribed: false,
    tags: ["eligible", "repeat"],
    source: "CSV Import",
    campaign_attempts: 0,
    updated_at: "2025-05-28T08:00:00.000Z",
    last_service_at: "2025-05-28T08:00:00.000Z",
  },
  {
    id: "contact-4",
    customer_name: "Priya Patel",
    first_name: "Priya",
    last_name: "Patel",
    phone_e164: null,
    email_normalized: "priya.patel@example.com",
    sms_opt_out: true,
    email_unsubscribed: true,
    tags: ["opted_out"],
    source: "Manual",
    campaign_attempts: 1,
    updated_at: "2025-05-20T10:00:00.000Z",
    last_service_at: "2025-05-18T11:15:00.000Z",
  },
  {
    id: "contact-5",
    customer_name: "Tom Wallace",
    first_name: "Tom",
    last_name: "Wallace",
    phone_e164: "+15715550534",
    email_normalized: "tom.wallace@example.com",
    sms_opt_out: false,
    email_unsubscribed: false,
    tags: ["same-day", "eligible"],
    source: "Website",
    last_contacted_at: "2025-06-03T09:00:00.000Z",
    campaign_attempts: 1,
    updated_at: "2025-06-03T09:00:00.000Z",
    last_service_at: "2025-06-03T08:00:00.000Z",
    campaign_status: "Post-Service Follow-Up Step 1 of 3",
  },
  {
    id: "contact-6",
    customer_name: "Lisa Chang",
    first_name: "Lisa",
    last_name: "Chang",
    phone_e164: "+15715550608",
    email_normalized: "lisa.chang@example.com",
    sms_opt_out: false,
    email_unsubscribed: false,
    tags: ["reviewed", "google", "repeat"],
    source: "Housecall Pro",
    last_contacted_at: "2025-05-25T14:00:00.000Z",
    campaign_attempts: 2,
    review_completion: { rating: 4 },
    updated_at: "2025-05-26T08:00:00.000Z",
    last_service_at: "2025-05-24T13:00:00.000Z",
    campaign_status: "Completed",
  },
  {
    id: "contact-7",
    customer_name: "Robert Klein",
    first_name: "Robert",
    last_name: "Klein",
    phone_e164: "+15715550721",
    email_normalized: "robert.klein@example.com",
    sms_opt_out: false,
    email_unsubscribed: false,
    tags: ["new"],
    source: "Referral",
    campaign_attempts: 0,
    updated_at: "2025-06-04T10:00:00.000Z",
    last_service_at: "2025-06-04T09:30:00.000Z",
  },
  {
    id: "contact-8",
    customer_name: "Angela Moore",
    first_name: "Angela",
    last_name: "Moore",
    phone_e164: "+15715550893",
    email_normalized: "angela.moore@example.com",
    sms_opt_out: false,
    email_unsubscribed: false,
    tags: ["repeat", "eligible"],
    source: "Housecall Pro",
    last_contacted_at: "2025-06-05T11:00:00.000Z",
    campaign_attempts: 1,
    updated_at: "2025-06-05T11:00:00.000Z",
    last_service_at: "2025-06-04T14:00:00.000Z",
    campaign_status: "Post-Service Follow-Up Step 2 of 3",
  },
];

export type ReputationAutomationPreviewData = {
  metrics: {
    active: number;
    activeRunning?: number;
    fired30d: number;
    fired30dTrend?: number;
    enrolled: number;
    enrolledTrend?: number;
    reviewsGenerated: number;
    reviewsGeneratedTrend?: number;
    successPct: number;
    successPctDelta?: number;
  };
  triggers: Array<{
    id: string;
    name: string;
    source: string;
    campaign: string;
    status: "Active" | "Paused" | "Test" | "Draft";
    lastFired: string | null;
    enrolled: number;
  }>;
  activities: Array<{ id: string; title: string; detail: string; at: string; tone?: "green" | "amber" | "red" }>;
  integrations: Array<{ id: string; name: string; status: "Connected" | "Available"; detail: string }>;
};

export const reputationAutomationsPreviewData: ReputationAutomationPreviewData = {
  metrics: {
    active: 7,
    activeRunning: 5,
    fired30d: 1248,
    fired30dTrend: 18,
    enrolled: 642,
    enrolledTrend: 21,
    reviewsGenerated: 32,
    reviewsGeneratedTrend: 23,
    successPct: 98.2,
    successPctDelta: -2.1,
  },
  triggers: [
    {
      id: "auto-1",
      name: "Job Marked Complete",
      source: "Housecall Pro CRM",
      campaign: "Post-Service Follow-Up (SMS • 3 steps)",
      status: "Active",
      lastFired: "2025-05-31T18:14:00.000Z",
      enrolled: 156,
    },
    {
      id: "auto-2",
      name: "New Webhook Received",
      source: "Zapier",
      campaign: "Review Request Email",
      status: "Active",
      lastFired: "2025-06-05T15:42:00.000Z",
      enrolled: 84,
    },
    {
      id: "auto-3",
      name: "Tag Applied",
      source: "GoHighLevel",
      campaign: "VIP Follow-Up Sequence",
      status: "Paused",
      lastFired: "2025-05-15T11:09:00.000Z",
      enrolled: 62,
    },
    {
      id: "auto-4",
      name: "Lead Source Trigger",
      source: "Google Sheets",
      campaign: "Industry Starter SMS",
      status: "Draft",
      lastFired: null,
      enrolled: 0,
    },
  ],
  activities: [
    { id: "act-1", title: "156 contacts enrolled", detail: "Job Marked Complete → Post-Service Follow-Up", at: "10 min ago", tone: "green" },
    { id: "act-2", title: "Webhook test succeeded", detail: "Housecall Pro payload mapping verified", at: "2 hr ago", tone: "green" },
    { id: "act-3", title: "Tag Applied trigger paused", detail: "GoHighLevel — awaiting reconnect", at: "Yesterday", tone: "amber" },
    { id: "act-4", title: "84 contacts enrolled", detail: "New Webhook Received → Review Request Email", at: "Yesterday", tone: "green" },
    { id: "act-5", title: "4 duplicates suppressed", detail: "Duplicate window protected recent contacts", at: "2 days ago", tone: "amber" },
  ],
  integrations: [
    { id: "int-1", name: "Housecall Pro", status: "Connected", detail: "Job completion events" },
    { id: "int-2", name: "Zapier", status: "Connected", detail: "2 active zaps" },
    { id: "int-3", name: "GoHighLevel", status: "Connected", detail: "CRM integration active" },
    { id: "int-4", name: "Google Sheets", status: "Connected", detail: "Webhook template ready" },
  ],
};

export const reputationAlertsPreviewData: ReputationAlertsData = {
  businessId: REPUTATION_PREVIEW_BUSINESS_ID,
  businessName: REPUTATION_PREVIEW_BUSINESS_NAME,
  activeAlerts: [
    {
      id: "alert-1",
      source: "synthesized",
      category: "unanswered_negative",
      severity: "critical",
      title: "2-star review needs a response",
      body: "Customer mentioned missed arrival window and damaged hallway paint. Posted 3 days ago with no reply.",
      recommendedAction: "Reply today, apologize for the missed window, and offer a direct resolution.",
      status: "active",
      createdAt: "2025-06-05T13:12:00.000Z",
      resolvedAt: null,
    },
    {
      id: "alert-2",
      source: "synthesized",
      category: "no_reviews",
      severity: "critical",
      title: "No new reviews in 14 days",
      body: "Your last review was received 14 days ago. At this pace your monthly velocity will drop below competitor average.",
      recommendedAction: "Launch a review request cohort for jobs completed in the last 14 days.",
      status: "active",
      createdAt: "2025-06-04T09:00:00.000Z",
      resolvedAt: null,
    },
    {
      id: "alert-3",
      source: "persisted",
      category: "rating_changed",
      severity: "critical",
      title: "Rating dropped from 4.7 to 4.6",
      body: "Two low-rated reviews in the last 7 days pulled your average below 4.65, triggering a display change on Google.",
      recommendedAction: "Respond to both low-rated reviews and accelerate positive review requests this week.",
      status: "active",
      createdAt: "2025-06-03T11:00:00.000Z",
      resolvedAt: null,
    },
    {
      id: "alert-4",
      source: "synthesized",
      category: "response_overdue",
      severity: "critical",
      title: "Response overdue — 5 reviews unanswered 10+ days",
      body: "5 reviews (including 2 negative) have received no owner response for more than 10 days.",
      recommendedAction: "Prioritize responding to negative reviews first, then thank positive reviewers.",
      status: "active",
      createdAt: "2025-06-02T14:30:00.000Z",
      resolvedAt: null,
    },
    {
      id: "alert-5",
      source: "persisted",
      category: "velocity_drop",
      severity: "medium",
      title: "Review velocity dropped below competitor pace",
      body: "You gained 6 reviews in the last 30 days while the local benchmark gained 11. Gap is widening.",
      recommendedAction: "Launch a short review request cohort for recent completed jobs.",
      status: "active",
      createdAt: "2025-06-01T10:00:00.000Z",
      resolvedAt: null,
    },
    {
      id: "alert-6",
      source: "synthesized",
      category: "competitor_velocity_spike",
      severity: "medium",
      title: "Competitor spike — All Star Junk gained 12 reviews",
      body: "All Star Junk gained 12 reviews in the past 7 days, pulling ahead by 8 in monthly velocity.",
      recommendedAction: "Increase review request volume this week to match the competitor pace.",
      status: "active",
      createdAt: "2025-06-01T08:00:00.000Z",
      resolvedAt: null,
    },
    {
      id: "alert-7",
      source: "persisted",
      category: "review_gap_widening",
      severity: "medium",
      title: "Gap widening vs Capital City Junk",
      body: "Capital City Junk leads by 87 reviews and is adding 14 per month vs your 8. Catch-up estimate: 18 months.",
      recommendedAction: "Run a targeted campaign to accelerate review velocity above 12 per month.",
      status: "active",
      createdAt: "2025-05-31T16:00:00.000Z",
      resolvedAt: null,
    },
    {
      id: "alert-8",
      source: "persisted",
      category: "campaign_delivery_problem",
      severity: "medium",
      title: "Campaign delivery rate dropped to 82%",
      body: "Carrier filtering increased on the 'Post-Service Follow-Up' template. 18% of SMS messages are failing.",
      recommendedAction: "Shorten the message and avoid promotional language to reduce carrier filtering.",
      status: "active",
      createdAt: "2025-05-30T12:00:00.000Z",
      resolvedAt: null,
    },
    {
      id: "alert-9",
      source: "synthesized",
      category: "unanswered_negative",
      severity: "medium",
      title: "3 negative reviews without responses this week",
      body: "Three 2-3 star reviews posted this week have no owner response. Potential customers will see unanswered complaints.",
      recommendedAction: "Respond to all three reviews with specific acknowledgment and resolution offers.",
      status: "active",
      createdAt: "2025-05-29T09:00:00.000Z",
      resolvedAt: null,
    },
    {
      id: "alert-10",
      source: "synthesized",
      category: "velocity_drop",
      severity: "medium",
      title: "Review request open rate below 20%",
      body: "SMS open rate for the 'Friendly – Short & Sweet' template dropped to 17%. Click-through is also down.",
      recommendedAction: "A/B test a shorter message body and a different send time.",
      status: "active",
      createdAt: "2025-05-28T15:00:00.000Z",
      resolvedAt: null,
    },
    {
      id: "alert-11",
      source: "persisted",
      category: "maps_visibility_moved",
      severity: "medium",
      title: "Maps visibility rank dropped 2 positions",
      body: "Your local pack ranking dropped from position 3 to position 5 in the last scan on the northwest grid.",
      recommendedAction: "Increase review velocity and ensure all profile fields are complete.",
      status: "active",
      createdAt: "2025-05-27T11:00:00.000Z",
      resolvedAt: null,
    },
    {
      id: "alert-12",
      source: "persisted",
      category: "campaign_delivery_problem",
      severity: "medium",
      title: "Automation trigger failed 3 times",
      body: "The GoHighLevel Tag Applied trigger failed 3 consecutive times. Contacts may have missed enrollment.",
      recommendedAction: "Reconnect the GoHighLevel integration and manually enroll missed contacts.",
      status: "active",
      createdAt: "2025-05-26T08:00:00.000Z",
      resolvedAt: null,
    },
  ],
  resolvedAlerts: [
    {
      id: "alert-r1",
      source: "persisted",
      category: "response_overdue",
      severity: "medium",
      title: "Positive reviews were waiting on replies",
      body: "Four positive reviews had no owner response for more than 10 days.",
      recommendedAction: "Thank the reviewers and mention specific service details.",
      status: "resolved",
      createdAt: "2025-05-10T12:00:00.000Z",
      resolvedAt: "2025-05-14T09:20:00.000Z",
    },
    {
      id: "alert-r2",
      source: "synthesized",
      category: "velocity_drop",
      severity: "medium",
      title: "Review velocity recovered",
      body: "Monthly velocity returned above 10 reviews after campaign launch.",
      recommendedAction: null,
      status: "resolved",
      createdAt: "2025-05-08T08:00:00.000Z",
      resolvedAt: "2025-05-20T16:00:00.000Z",
    },
    {
      id: "alert-r3",
      source: "persisted",
      category: "unanswered_negative",
      severity: "critical",
      title: "1-star review responded and resolved",
      body: "Customer complaint about scheduling addressed and refund offered.",
      recommendedAction: null,
      status: "resolved",
      createdAt: "2025-05-05T10:00:00.000Z",
      resolvedAt: "2025-05-06T14:30:00.000Z",
    },
    {
      id: "alert-r4",
      source: "persisted",
      category: "campaign_delivery_problem",
      severity: "medium",
      title: "SMS delivery issue resolved",
      body: "Template updated to remove flagged language. Delivery rate returned to 96%.",
      recommendedAction: null,
      status: "resolved",
      createdAt: "2025-05-01T09:00:00.000Z",
      resolvedAt: "2025-05-03T11:00:00.000Z",
    },
  ],
  preferences: {
    every_new_review: true,
    low_rating_only: false,
    unanswered_only: false,
    daily_summary: false,
    weekly_summary: true,
    no_reviews_days: 14,
    email_recipients: ["ops@ateamjunk.com", "owner@ateamjunk.com"],
    velocity_drop: true,
    competitor_velocity_spike: true,
    rating_changed: true,
    response_overdue: true,
    campaign_delivery_problem: true,
    review_gap_widening: true,
    maps_visibility_moved: true,
  },
  previewMetrics: {
    activeCount: 12,
    criticalCount: 4,
    warningCount: 8,
    infoCount: 0,
    requiringAction: 7,
    resolved30d: 28,
    notificationsSent: 156,
    alertAccuracy: 96,
  },
};

export const reputationAuditPreviewData: ReputationModulesAuditData = {
  businessId: REPUTATION_PREVIEW_BUSINESS_ID,
  businessName: REPUTATION_PREVIEW_BUSINESS_NAME,
  generatedAt: "2025-06-08T02:00:00.000Z",
  analytics: {
    businessId: REPUTATION_PREVIEW_BUSINESS_ID,
    businessName: REPUTATION_PREVIEW_BUSINESS_NAME,
    timezone: "America/New_York",
    lastSyncedAt: "2025-06-07T20:00:00.000Z",
    groupModes: ["daily", "weekly", "monthly"],
    competitors: [
      { id: "comp-1", name: "Capital City Junk" },
      { id: "comp-2", name: "Haul Masters" },
    ],
    timelinePoints: [
      { date: "2025-04-01", you: 3, competitorAvg: 5, events: [] },
      { date: "2025-04-15", you: 6, competitorAvg: 7, events: [] },
      { date: "2025-05-01", you: 8, competitorAvg: 9, events: [] },
      { date: "2025-05-15", you: 11, competitorAvg: 11, events: [] },
      { date: "2025-06-01", you: 14, competitorAvg: 12, events: [] },
      { date: "2025-06-08", you: 16, competitorAvg: 13, events: [] },
    ],
    timelineByCompetitor: { "comp-1": [5, 7, 9, 11, 12, 13] },
    timelineEvents: [],
    weeklyVelocity: 4.2,
    monthlyVelocity: 16,
    rolling7d: 8,
    rolling30d: 32,
    rolling60d: 58,
    rolling90d: 82,
    rollingPeriods: [
      { days: 7, current: 8, previous: 6, delta: 2, deltaPct: 33.3 },
      { days: 30, current: 32, previous: 24, delta: 8, deltaPct: 33.3 },
      { days: 60, current: 58, previous: 44, delta: 14, deltaPct: 31.8 },
      { days: 90, current: 82, previous: 63, delta: 19, deltaPct: 30.2 },
    ],
    priorPeriod: {
      rolling7d: 6,
      rolling30d: 24,
      rolling60d: 44,
      rolling90d: 63,
      rolling7dDelta: 2,
      rolling30dDelta: 8,
      rolling60dDelta: 14,
      rolling90dDelta: 19,
      weeklyVelocityDelta: 0.8,
      monthlyVelocityDelta: 4,
    },
    responseRate: 94,
    avgResponseTimeDays: 1.2,
    avgDaysBetweenReviews: 1.4,
    medianDaysBetweenReviews: 1,
    longestDroughtDays: 4,
    activeStreakDays: 14,
    accelerationPct: 33.3,
    momentumStatus: "Accelerating",
    momentumLabel: "Accelerating",
    drivers: ["32 reviews in 30 days", "Ahead of competitor monthly average (32 vs 21)", "Response rate at 94% — well above industry avg"],
    explanation: "Review velocity is accelerating strongly and response coverage is industry-leading. Competitor #1 still requires sustained effort to close the 87-review gap.",
    competitorRelative: "Ahead of local 30-day benchmark",
  },
  competitors: {
    businessId: REPUTATION_PREVIEW_BUSINESS_ID,
    businessName: REPUTATION_PREVIEW_BUSINESS_NAME,
    leaderboardRows: [
      {
        id: "comp-1",
        name: "Capital City Junk",
        isYou: false,
        totalReviews: 335,
        rating: 4.8,
        reviews30: 14,
        reviews60: 28,
        reviews90: 42,
        reviewsPerMonth: 14,
        momentumLabel: "Stable",
        responseRate: 71,
        responseSpeedDaysAvg: 3.4,
      },
      {
        id: "comp-2",
        name: "Haul Masters",
        isYou: false,
        totalReviews: 285,
        rating: 4.7,
        reviews30: 11,
        reviews60: 22,
        reviews90: 33,
        reviewsPerMonth: 11,
        momentumLabel: "Stable",
        responseRate: 58,
        responseSpeedDaysAvg: 4.1,
      },
      {
        id: REPUTATION_PREVIEW_BUSINESS_ID,
        name: REPUTATION_PREVIEW_BUSINESS_NAME,
        isYou: true,
        totalReviews: 248,
        rating: 4.6,
        reviews30: 32,
        reviews60: 58,
        reviews90: 82,
        reviewsPerMonth: 32,
        momentumLabel: "Accelerating",
        responseRate: 94,
        responseSpeedDaysAvg: 1.2,
      },
      {
        id: "comp-4",
        name: "All Star Junk",
        isYou: false,
        totalReviews: 218,
        rating: 4.4,
        reviews30: 9,
        reviews60: 18,
        reviews90: 27,
        reviewsPerMonth: 9,
        momentumLabel: "Healthy",
        responseRate: 61,
        responseSpeedDaysAvg: 3.8,
      },
      {
        id: "comp-5",
        name: "EcoHaul Pro",
        isYou: false,
        totalReviews: 187,
        rating: 4.5,
        reviews30: 7,
        reviews60: 14,
        reviews90: 21,
        reviewsPerMonth: 7,
        momentumLabel: "Stable",
        responseRate: 55,
        responseSpeedDaysAvg: 5.2,
      },
      {
        id: "comp-6",
        name: "Junk Away",
        isYou: false,
        totalReviews: 156,
        rating: 4.2,
        reviews30: 5,
        reviews60: 10,
        reviews90: 15,
        reviewsPerMonth: 5,
        momentumLabel: "Slowing",
        responseRate: 42,
        responseSpeedDaysAvg: 7.1,
      },
      {
        id: "comp-7",
        name: "Quick Clear",
        isYou: false,
        totalReviews: 142,
        rating: 4.3,
        reviews30: 4,
        reviews60: 8,
        reviews90: 12,
        reviewsPerMonth: 4,
        momentumLabel: "Slowing",
        responseRate: 38,
        responseSpeedDaysAvg: 8.3,
      },
    ],
    gapRows: [
      {
        competitorId: "comp-1",
        competitorName: "Capital City Junk",
        totalGap: 87,
        monthlyVelocityGap: -18,
        neededToCatch: 87,
        pace3Months: 96,
        pace6Months: 192,
        pace12Months: 384,
        estimatedCatchUp: "18 months at current pace",
        estimatedCatchUpDate: "2026-12-01",
        estimatedCatchUpMonths: 18,
        warning: null,
        gapExpanding: false,
      },
      {
        competitorId: "comp-2",
        competitorName: "Haul Masters",
        totalGap: 37,
        monthlyVelocityGap: -21,
        neededToCatch: 37,
        pace3Months: 96,
        pace6Months: 192,
        pace12Months: 384,
        estimatedCatchUp: "2 months at current pace",
        estimatedCatchUpDate: "2025-08-01",
        estimatedCatchUpMonths: 2,
        warning: null,
        gapExpanding: false,
      },
      {
        competitorId: "comp-4",
        competitorName: "All Star Junk",
        totalGap: 0,
        monthlyVelocityGap: -23,
        neededToCatch: 0,
        pace3Months: 96,
        pace6Months: 192,
        pace12Months: 384,
        estimatedCatchUp: "Already ahead",
        estimatedCatchUpDate: null,
        estimatedCatchUpMonths: 0,
        warning: null,
        gapExpanding: false,
      },
    ],
    complaintPatterns: [
      { theme: "Scheduling", competitorMentions: 18, yourMentions: 7, gap: 11 },
      { theme: "Pricing clarity", competitorMentions: 13, yourMentions: 5, gap: 8 },
    ],
    positioningOpportunities: [
      { title: "Position around punctual arrival windows", description: "Competitors are criticized for missed windows. Highlight same-day updates in replies and campaigns.", sourceTheme: "Scheduling" },
      { title: "Use transparent pricing language", description: "Mention upfront estimates and no-surprise pricing in owner responses.", sourceTheme: "Pricing clarity" },
    ],
    strengths: {
      positive: [{ label: "Professional crew", count: 89 }, { label: "Fast removal", count: 72 }, { label: "Careful cleanup", count: 54 }],
      negative: [{ label: "Arrival window", count: 7 }, { label: "Quote clarity", count: 5 }],
      competitorPositive: [{ label: "Low price", count: 61 }],
      competitorNegative: [{ label: "Scheduling", count: 18 }, { label: "Communication", count: 14 }],
      serviceGaps: [{ label: "Estate cleanout", yourMentions: 14, competitorMentions: 28, gap: 14 }],
      frequentlyPraisedServices: [{ term: "garage cleanout", count: 42 }, { term: "furniture removal", count: 31 }],
      frequentlyMentionedEmployees: [{ term: "Carlos", count: 18 }, { term: "Bree", count: 15 }],
    },
    contentComparison: {
      you: { avgLength: 142, pctWithText: 92, locationTerms: 44, serviceTerms: 76, employeeMentions: 33, pctGeneric: 6, pctDetailed: 81 },
      competitors: { avgLength: 118, pctWithText: 79, locationTerms: 31, serviceTerms: 62, employeeMentions: 20, pctGeneric: 24, pctDetailed: 55 },
    },
  },
  insights: {
    businessId: REPUTATION_PREVIEW_BUSINESS_ID,
    businessName: REPUTATION_PREVIEW_BUSINESS_NAME,
    metrics: {
      positiveThemeMentions: 215,
      negativeThemeMentions: 18,
      totalReviewText: 248,
      avgReviewLength: 142,
      reviewsWithPhotos: 37,
      employeeMentions: 33,
    },
    themes: {
      positive: [
        { label: "Professional crew", count: 89, pct: 36 },
        { label: "Fast removal", count: 72, pct: 29 },
        { label: "Careful cleanup", count: 54, pct: 22 },
        { label: "Great communication", count: 38, pct: 15 },
      ],
      negative: [
        { label: "Arrival window", count: 7, pct: 2.8 },
        { label: "Quote clarity", count: 5, pct: 2 },
        { label: "Scheduling delays", count: 4, pct: 1.6 },
      ],
      emerging: [
        { label: "Same-day availability", count: 19, pct: 7.7, delta: 8 },
        { label: "Donation handling", count: 11, pct: 4.4, delta: 5 },
      ],
      themeFrequencyOverTime: [{ label: "Professional crew", recent30: 24, prior30: 16, delta: 8 }],
      competitorThemes: [{ label: "Scheduling", yourCount: 7, competitorCount: 18, competitorAvg: 9, gap: 11 }],
    },
    servicesAndKeywords: [{ keyword: "garage cleanout", count: 42 }, { keyword: "furniture removal", count: 31 }],
    categorizedKeywords: {
      services: [{ keyword: "garage cleanout", count: 42 }],
      cities: [{ keyword: "Arlington", count: 22 }],
      employees: [{ keyword: "Carlos", count: 18 }],
      pricing: [{ keyword: "fair price", count: 22 }],
      speed: [{ keyword: "same day", count: 19 }],
      communication: [{ keyword: "text updates", count: 16 }],
    },
    responsePerformance: {
      responseRate: 94,
      totalWithText: 248,
      answered: 233,
      unansweredPositive: 12,
      unansweredNegative: 3,
      unansweredNeutral: 2,
      avgResponseTimeDays: 1.2,
      positiveResponseRate: 96,
      negativeResponseRate: 82,
      oldestUnansweredAt: "2025-05-29T12:00:00.000Z",
      oldestUnansweredDays: 10,
    },
    responseQuality: {
      genericResponseSuspected: 8,
      genericResponsePct: 3,
      qualitySummary: {
        personalizedPct: 88,
        genericPct: 6,
        copyPastePct: 4,
        defensiveCount: 1,
        addressesIssuePct: 91,
        offersResolutionPct: 76,
      },
      rows: [],
    },
  },
  alerts: reputationAlertsPreviewData,
  mapsVisibility: {
    latestScanId: "scan-preview-82",
    latestFinishedAt: "2025-06-06T19:00:00.000Z",
    latestStatus: "completed",
    scanCount30d: 6,
    gridSize: 49,
    summary: "Top-3 visibility improved on 68% of tracked cells after recent review gains.",
    aggregateMetrics: { avgRank: 4.8, top3Pct: 68, top10Pct: 91 },
  },
  campaignCohorts: [
    { campaignId: "camp-1", name: "Post-Service Follow-Up", status: "active", startedAt: "2025-05-10T12:00:00.000Z", createdAt: "2025-05-09T12:00:00.000Z", sentCount: 486, failedCount: 12, attributedCount: 62, confirmedCount: 44, likelyCount: 18 },
    { campaignId: "camp-2", name: "30-Day Follow-Up Email", status: "active", startedAt: "2025-05-15T12:00:00.000Z", createdAt: "2025-05-14T12:00:00.000Z", sentCount: 218, failedCount: 6, attributedCount: 38, confirmedCount: 26, likelyCount: 12 },
  ],
  recommendedActions: {
    days30: [
      "Respond to the 3 unanswered negative reviews to protect conversion.",
      "Launch a review request cohort for all jobs completed in the last 14 days.",
      "A/B test a shorter SMS body to recover the 82% delivery rate.",
      "Reconnect the GoHighLevel automation trigger to resume VIP enrollments.",
    ],
    days60: [
      "Sustain 12+ reviews per month to close the 37-review gap vs Haul Masters.",
      "Use competitor complaint themes (scheduling, pricing clarity) in owner response copy.",
      "Refresh response snippets to include service-specific detail and reviewer's first name.",
      "Run a second Maps visibility scan to measure rank improvement from recent velocity.",
    ],
    days90: [
      "Build a 90-day review plan to close the 87-review gap vs Capital City Junk.",
      "Establish a monthly competitor-gap report for the top three service areas.",
      "Expand team response training to maintain the 94% response rate as volume grows.",
      "Test a 3-step review sequence to increase conversion from 7.4% toward 15%.",
    ],
  },
};
