import type { CampaignRow } from "@/components/reputation/review-requests-campaigns";

export const REVIEW_CAMPAIGNS_PREVIEW_BUSINESS_ID = "preview-review-campaigns";

const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();

export const reviewCampaignsPreviewCampaigns: CampaignRow[] = [
  {
    id: "camp-preview-1",
    name: "Post-Service Follow-Up",
    status: "active",
    channel: "sms",
    created_at: daysAgo(18),
    recipients_total: 156,
    recipients_ready: 156,
    queued: 0,
    sent: 312,
    delivered: 305,
    failed: 7,
    clicked: 52,
    opted_out: 4,
    reviews_detected: 18,
    conversion_rate: 5.8,
    trigger_type: "webhook",
    trigger_config: { eventType: "service.completed" },
    next_step_label: "Step 2 in 2 days",
  },
  {
    id: "camp-preview-2",
    name: "Email Review Series",
    status: "active",
    channel: "email",
    created_at: daysAgo(14),
    recipients_total: 89,
    recipients_ready: 89,
    queued: 0,
    sent: 178,
    delivered: 172,
    failed: 6,
    clicked: 34,
    opted_out: 2,
    reviews_detected: 8,
    conversion_rate: 4.5,
    trigger_type: "manual",
    next_step_label: "Step 2 in 4 days",
  },
  {
    id: "camp-preview-3",
    name: "VIP Customer Follow-Up",
    status: "active",
    channel: "sms",
    created_at: daysAgo(10),
    recipients_total: 43,
    recipients_ready: 43,
    queued: 0,
    sent: 129,
    delivered: 125,
    failed: 4,
    clicked: 21,
    opted_out: 1,
    reviews_detected: 9,
    conversion_rate: 7.0,
    trigger_type: "manual",
    next_step_label: "Step 3 in 1 day",
  },
  {
    id: "camp-preview-4",
    name: "Google Review Boost",
    status: "paused",
    channel: "sms",
    created_at: daysAgo(22),
    recipients_total: 62,
    recipients_ready: 62,
    queued: 0,
    sent: 186,
    delivered: 179,
    failed: 7,
    clicked: 28,
    opted_out: 3,
    reviews_detected: 7,
    conversion_rate: 3.8,
    trigger_type: "manual",
    next_step_label: "Paused (Manual)",
  },
  {
    id: "camp-preview-5",
    name: "New Customer Welcome",
    status: "draft",
    channel: "email",
    created_at: daysAgo(2),
    recipients_total: 0,
    recipients_ready: 0,
    queued: 0,
    sent: 0,
    delivered: 0,
    failed: 0,
    clicked: 0,
    opted_out: 0,
    reviews_detected: 0,
    trigger_type: "manual",
    next_step_label: "Not started",
  },
  {
    id: "camp-preview-6",
    name: "Monthly Maintenance",
    status: "completed",
    channel: "email",
    created_at: daysAgo(45),
    completed_at: "2025-05-10T00:00:00Z",
    recipients_total: 74,
    recipients_ready: 74,
    queued: 0,
    sent: 222,
    delivered: 218,
    failed: 4,
    clicked: 38,
    opted_out: 2,
    reviews_detected: 16,
    conversion_rate: 7.2,
    trigger_type: "manual",
    next_step_label: "Completed May 10, 2025",
  },
];

export const reviewCampaignsPreviewStats = {
  activeCampaigns: 3,
  pausedCampaigns: 1,
  totalCampaigns: 6,
  messagesSent30d: 1248,
  messagesSentTrend: 18,
  reviewsGenerated30d: 32,
  reviewsTrend: 23,
  conversion: 7.3,
  conversionTrend: 1.2,
  costPerReview: 2.41,
  costTrend: -12,
};

export type ReviewCampaignsPreviewActivity = {
  id: string;
  type: "reviews_detected" | "sms_sent" | "review_received" | "campaign_paused";
  label: string;
  detail: string;
  relativeTime: string;
};

export const reviewCampaignsPreviewActivity: ReviewCampaignsPreviewActivity[] = [
  {
    id: "act-1",
    type: "reviews_detected",
    label: "3 new reviews detected",
    detail: "Post-Service Follow-Up campaign",
    relativeTime: "2h ago",
  },
  {
    id: "act-2",
    type: "sms_sent",
    label: "48 SMS messages sent",
    detail: "VIP Customer Follow-Up — Step 2 batch",
    relativeTime: "4h ago",
  },
  {
    id: "act-3",
    type: "review_received",
    label: "5-star review received",
    detail: "James W. · Junk Removal · Woodbridge VA",
    relativeTime: "6h ago",
  },
  {
    id: "act-4",
    type: "campaign_paused",
    label: "Google Review Boost paused",
    detail: "Manually paused — 62 recipients enrolled",
    relativeTime: "1d ago",
  },
  {
    id: "act-5",
    type: "sms_sent",
    label: "82 SMS messages sent",
    detail: "Post-Service Follow-Up — Step 1 batch",
    relativeTime: "1d ago",
  },
  {
    id: "act-6",
    type: "reviews_detected",
    label: "5 new reviews detected",
    detail: "Email Review Series campaign",
    relativeTime: "2d ago",
  },
];

export const reviewCampaignsPreviewResponse = {
  campaigns: reviewCampaignsPreviewCampaigns,
};
