import { DEFAULT_POSTER_CONFIG } from "@/lib/reputation/review-requests";

export const REVIEW_REQUESTS_PREVIEW_BUSINESS_ID = "preview-review-requests";

const now = new Date().toISOString();
const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();

export const reviewRequestsPreviewKit = {
  businessName: "Premier Junk Removal",
  placeId: "ChIJpreviewplaceid0001",
  link: {
    id: "link-preview-1",
    review_url: "https://search.google.com/local/writereview?placeid=ChIJpreviewplaceid0001",
    short_url: "premier-junk",
    place_id: "ChIJpreviewplaceid0001",
    poster_config: {
      ...DEFAULT_POSTER_CONFIG,
      title: "Love our service?",
      description: "Scan to leave a quick Google review",
      brandColor: "#137752",
      showFooter: true,
      selectedPhrases: ["junk removal", "same-day service", "professional crew"],
    },
  },
  posterConfig: {
    ...DEFAULT_POSTER_CONFIG,
    title: "Love our service?",
    description: "Scan to leave a quick Google review",
    brandColor: "#137752",
    showFooter: true,
    selectedPhrases: ["junk removal", "same-day service", "professional crew"],
  },
  mapsFallbackUrl: null,
  warning: null,
  templates: [
    {
      id: "tpl-sms-1",
      channel: "sms",
      name: "Post-job SMS",
      body: "Hi {{customer_name}} — thanks for choosing {{business_name}}! If we made your day easier, we'd love a quick Google review: {{review_link}}",
      is_default: true,
    },
    {
      id: "tpl-email-1",
      channel: "email",
      name: "Post-job email",
      subject: "We'd love your feedback!",
      body: "Hi {{customer_name}},\n\nThank you for trusting {{business_name}} with your recent {{service_type}}.\n\nIf you have 30 seconds, a Google review helps neighbors find us:\n{{review_link}}\n\nAppreciate you!",
      is_default: true,
    },
    {
      id: "tpl-generic-1",
      channel: "generic",
      name: "Generic copy/paste",
      body: "Thanks for choosing {{business_name}}! Leave a review here: {{review_link}}",
      is_default: true,
    },
  ],
  events: [
    {
      id: "evt-1",
      event_type: "sent",
      channel: "sms",
      customer_name: "Jane Smith",
      customer_phone: "+15551234001",
      service_type: "Junk Removal",
      created_at: daysAgo(1),
    },
    {
      id: "evt-2",
      event_type: "sent",
      channel: "email",
      customer_name: "Marcus Lee",
      customer_email: "marcus@example.com",
      service_type: "Hauling",
      created_at: daysAgo(2),
    },
  ],
  keywordSuggestions: [
    { id: "kw1", keyword: "junk removal", keyword_type: "service", gap: 18 },
    { id: "kw2", keyword: "same-day service", keyword_type: "theme", gap: 14 },
    { id: "kw3", keyword: "professional crew", keyword_type: "theme", gap: 12 },
    { id: "kw4", keyword: "garage cleanout", keyword_type: "service", gap: 9 },
    { id: "kw5", keyword: "furniture haul away", keyword_type: "service", gap: 8 },
  ],
};

export const reviewRequestsPreviewStats = {
  total_sent: 128,
  email_sent: 74,
  sms_sent: 46,
  manual_sent: 8,
  failed: 6,
  last_7_days: 22,
  last_30_days: 61,
  replies: 19,
  inbound_reply_domain: "reply.mapsgrowth.app",
  trial_sms_template: null,
  recent_sends: [
    {
      id: "send-1",
      channel: "email",
      recipient_email: "jane.smith@email.com",
      recipient_phone: null,
      status: "sent",
      message_body: "Hi Jane — thanks for choosing Premier Junk Removal! Leave a quick Google review…",
      sent_at: daysAgo(0),
      created_at: daysAgo(0),
      has_reply: true,
      review_request_contacts: { customer_name: "Jane Smith" },
    },
    {
      id: "send-2",
      channel: "sms",
      recipient_email: null,
      recipient_phone: "+15551234002",
      status: "sent",
      message_body: "Hi Marcus — thanks for choosing Premier Junk Removal! Review link…",
      sent_at: daysAgo(1),
      created_at: daysAgo(1),
      has_reply: false,
      review_request_contacts: { customer_name: "Marcus Lee" },
    },
    {
      id: "send-3",
      channel: "email",
      recipient_email: "priya@example.com",
      recipient_phone: null,
      status: "failed",
      message_body: "Hi Priya — we'd love your feedback on Google…",
      sent_at: daysAgo(2),
      created_at: daysAgo(2),
      has_reply: false,
      review_request_contacts: { customer_name: "Priya Patel" },
    },
    {
      id: "send-4",
      channel: "sms",
      recipient_email: null,
      recipient_phone: "+15551234004",
      status: "sent",
      message_body: "Hi Devon — appreciate your business. Quick Google review?",
      sent_at: daysAgo(3),
      created_at: daysAgo(3),
      has_reply: true,
      review_request_contacts: { customer_name: "Devon Brooks" },
    },
    {
      id: "send-5",
      channel: "email",
      recipient_email: "amy.nguyen@email.com",
      recipient_phone: null,
      status: "pending",
      message_body: "Hi Amy — thanks for the cleanout job. Review link inside…",
      sent_at: null,
      created_at: daysAgo(0),
      has_reply: false,
      review_request_contacts: { customer_name: "Amy Nguyen" },
    },
  ],
  recent_replies: [
    {
      id: "reply-1",
      send_id: "send-1",
      channel: "email",
      customer_name: "Jane Smith",
      customer_email: "jane.smith@email.com",
      reply_body: "Absolutely — happy to leave a review. Great crew!",
      from: "jane.smith@email.com",
      subject: "Re: We'd love your feedback!",
      created_at: daysAgo(0),
    },
    {
      id: "reply-2",
      send_id: "send-4",
      channel: "sms",
      customer_name: "Devon Brooks",
      customer_phone: "+15551234004",
      reply_body: "Done — left 5 stars.",
      from: "+15551234004",
      created_at: daysAgo(2),
    },
    {
      id: "reply-3",
      channel: "email",
      customer_name: "Sam Ortiz",
      customer_email: "sam@example.com",
      reply_body: "Can you resend the link? I think I deleted it.",
      from: "sam@example.com",
      subject: "Review request",
      created_at: daysAgo(4),
    },
  ],
};

export const reviewRequestsPreviewCampaigns = {
  campaigns: [
    {
      id: "camp-1",
      name: "June Closed Jobs",
      status: "active",
      channel: "both",
      created_at: daysAgo(12),
      recipients_total: 84,
      recipients_ready: 76,
      queued: 18,
      sent: 52,
      failed: 3,
      clicked: 21,
      opted_out: 2,
    },
    {
      id: "camp-2",
      name: "HOA Cleanouts Batch",
      status: "paused",
      channel: "email",
      created_at: daysAgo(20),
      recipients_total: 40,
      recipients_ready: 38,
      queued: 0,
      sent: 22,
      failed: 1,
      clicked: 9,
      opted_out: 1,
    },
    {
      id: "camp-3",
      name: "Spring Garage Sweep",
      status: "completed",
      channel: "sms",
      created_at: daysAgo(45),
      recipients_total: 55,
      recipients_ready: 55,
      queued: 0,
      sent: 54,
      failed: 1,
      clicked: 17,
      opted_out: 0,
    },
  ],
};

export { now };
