import type { CampaignRow } from "@/components/reputation/review-requests-campaigns";

export const REVIEW_CAMPAIGNS_PREVIEW_BUSINESS_ID = "preview-review-campaigns";

const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();

export const reviewCampaignsPreviewCampaigns: CampaignRow[] = [
  {
    id: "camp-preview-1",
    name: "Post-Job Automation",
    status: "active",
    channel: "both",
    created_at: daysAgo(3),
    recipients_total: 180,
    recipients_ready: 164,
    queued: 28,
    sent: 136,
    delivered: 129,
    failed: 4,
    clicked: 58,
    opted_out: 3,
    reviews_detected: 24,
    trigger_type: "webhook",
    trigger_config: { eventType: "job.completed" },
  },
  {
    id: "camp-preview-2",
    name: "June Cleanout Follow-Up",
    status: "scheduled",
    channel: "sms",
    created_at: daysAgo(8),
    recipients_total: 92,
    recipients_ready: 88,
    queued: 88,
    sent: 0,
    delivered: 0,
    failed: 0,
    clicked: 0,
    opted_out: 0,
    reviews_detected: 0,
    trigger_type: "manual",
  },
  {
    id: "camp-preview-3",
    name: "HOA Bulk Request",
    status: "paused",
    channel: "email",
    created_at: daysAgo(14),
    recipients_total: 74,
    recipients_ready: 70,
    queued: 12,
    sent: 58,
    delivered: 56,
    failed: 2,
    clicked: 21,
    opted_out: 1,
    reviews_detected: 8,
    trigger_type: "manual",
  },
  {
    id: "camp-preview-4",
    name: "Spring Garage Sweep",
    status: "completed",
    channel: "both",
    created_at: daysAgo(31),
    completed_at: daysAgo(18),
    recipients_total: 120,
    recipients_ready: 118,
    queued: 0,
    sent: 118,
    delivered: 111,
    failed: 5,
    clicked: 49,
    opted_out: 2,
    reviews_detected: 19,
    trigger_type: "manual",
  },
  {
    id: "camp-preview-5",
    name: "Estate Cleanout Draft",
    status: "draft",
    channel: "email",
    created_at: daysAgo(1),
    recipients_total: 46,
    recipients_ready: 0,
    queued: 0,
    sent: 0,
    delivered: 0,
    failed: 0,
    clicked: 0,
    opted_out: 0,
    reviews_detected: 0,
    trigger_type: "manual",
  },
];

export const reviewCampaignsPreviewResponse = {
  campaigns: reviewCampaignsPreviewCampaigns,
};
