import { DEFAULT_POSTER_CONFIG } from "@/lib/reputation/review-requests";

export const REVIEW_REQUESTS_PREVIEW_BUSINESS_ID = "preview-review-requests";

const now = new Date().toISOString();
const daysAgo = (n: number) => new Date(Date.now() - n * 86400000).toISOString();

export const reviewRequestsPreviewKit = {
  businessName: "Premier Junk Removal",
  placeId: "ChIJpreviewplaceid0001",
  sendFromNumber: "+1 (571) 555-0199",
  sendFromVerified: true,
  eligibleCount: 156,
  link: {
    id: "link-preview-1",
    review_url: "https://search.google.com/local/writereview?placeid=ChIJpreviewplaceid0001",
    short_url: "premier-junk",
    place_id: "ChIJpreviewplaceid0001",
    poster_config: {
      ...DEFAULT_POSTER_CONFIG,
      title: "Love our service?",
      description: "Scan to leave a quick Google review",
      brandColor: "#16A34A",
      showFooter: true,
      selectedPhrases: ["junk removal", "same-day service", "professional crew"],
    },
  },
  posterConfig: {
    ...DEFAULT_POSTER_CONFIG,
    title: "Love our service?",
    description: "Scan to leave a quick Google review",
    brandColor: "#16A34A",
    showFooter: true,
    selectedPhrases: ["junk removal", "same-day service", "professional crew"],
  },
  mapsFallbackUrl: null,
  warning: null,
  templates: [
    {
      id: "tpl-friendly-1",
      channel: "sms",
      name: "Friendly – Short & Sweet",
      body: "Hi {first_name}! Thanks for choosing {business_name}. If we made your day easier, we'd love a quick Google review: {review_link} — means the world to our small team! 🙏",
      is_default: true,
      bestUsed: "1–3 days after service",
      avgConversion: 7.8,
      charCount: 134,
    },
    {
      id: "tpl-sms-2",
      channel: "sms",
      name: "Post-Job Reminder",
      body: "Hi {first_name} — thanks for choosing {business_name}! If you had a great experience, we'd love your Google review: {review_link}",
      is_default: false,
      bestUsed: "1–5 days after service",
      avgConversion: 6.2,
      charCount: 118,
    },
    {
      id: "tpl-email-1",
      channel: "email",
      name: "Post-job Email",
      subject: "We'd love your feedback!",
      body: "Hi {first_name},\n\nThank you for trusting {business_name} with your recent service.\n\nIf you have 30 seconds, a Google review helps neighbors find us:\n{review_link}\n\nAppreciate you!",
      is_default: false,
      bestUsed: "2–5 days after service",
      avgConversion: 5.4,
      charCount: 201,
    },
  ],
  selectedContacts: [
    { id: "c-01", name: "James Whitfield", phone: "+1 (571) 555-0101", lastService: "Junk Removal", tags: ["Completed", "No Request Sent"] },
    { id: "c-02", name: "Maria Santos", phone: "+1 (571) 555-0102", lastService: "Furniture Removal", tags: ["Completed", "Eligible"] },
    { id: "c-03", name: "Tyler Brooks", phone: "+1 (703) 555-0103", lastService: "Garage Cleanout", tags: ["Completed", "Has Consent"] },
    { id: "c-04", name: "Priya Patel", phone: "+1 (571) 555-0104", lastService: "Junk Removal", tags: ["Completed", "Eligible"] },
    { id: "c-05", name: "Devon Clarke", phone: "+1 (703) 555-0105", lastService: "Appliance Removal", tags: ["Completed", "No Request Sent"] },
    { id: "c-06", name: "Ashley Kim", phone: "+1 (571) 555-0106", lastService: "Mattress Disposal", tags: ["Completed", "Eligible"] },
    { id: "c-07", name: "Marcus Rivera", phone: "+1 (703) 555-0107", lastService: "Junk Removal", tags: ["Completed", "Has Consent"] },
    { id: "c-08", name: "Samantha Lee", phone: "+1 (571) 555-0108", lastService: "Estate Cleanout", tags: ["Completed", "Eligible"] },
    { id: "c-09", name: "Jordan Murphy", phone: "+1 (703) 555-0109", lastService: "Junk Removal", tags: ["Completed", "No Request Sent"] },
    { id: "c-10", name: "Rachel Torres", phone: "+1 (571) 555-0110", lastService: "Furniture Removal", tags: ["Completed", "Eligible"] },
    { id: "c-11", name: "Kevin Nguyen", phone: "+1 (703) 555-0111", lastService: "Garage Cleanout", tags: ["Completed", "Has Consent"] },
    { id: "c-12", name: "Lisa Johnson", phone: "+1 (571) 555-0112", lastService: "Junk Removal", tags: ["Completed", "Eligible"] },
    { id: "c-13", name: "Brian Foster", phone: "+1 (703) 555-0113", lastService: "Appliance Removal", tags: ["Completed", "No Request Sent"] },
    { id: "c-14", name: "Michelle Davis", phone: "+1 (571) 555-0114", lastService: "Junk Removal", tags: ["Completed", "Eligible"] },
    { id: "c-15", name: "Chris Thompson", phone: "+1 (703) 555-0115", lastService: "Hot Tub Removal", tags: ["Completed", "Has Consent"] },
    { id: "c-16", name: "Amanda Wilson", phone: "+1 (571) 555-0116", lastService: "Junk Removal", tags: ["Completed", "Eligible"] },
    { id: "c-17", name: "Robert Martinez", phone: "+1 (703) 555-0117", lastService: "Estate Cleanout", tags: ["Completed", "No Request Sent"] },
    { id: "c-18", name: "Nicole Brown", phone: "+1 (571) 555-0118", lastService: "Furniture Removal", tags: ["Completed", "Eligible"] },
    { id: "c-19", name: "Daniel Taylor", phone: "+1 (703) 555-0119", lastService: "Junk Removal", tags: ["Completed", "Has Consent"] },
    { id: "c-20", name: "Stephanie Harris", phone: "+1 (571) 555-0120", lastService: "Garage Cleanout", tags: ["Completed", "Eligible"] },
    { id: "c-21", name: "Anthony Jackson", phone: "+1 (703) 555-0121", lastService: "Appliance Removal", tags: ["Completed", "No Request Sent"] },
    { id: "c-22", name: "Jennifer White", phone: "+1 (571) 555-0122", lastService: "Junk Removal", tags: ["Completed", "Eligible"] },
    { id: "c-23", name: "William Clark", phone: "+1 (703) 555-0123", lastService: "Mattress Disposal", tags: ["Completed", "Has Consent"] },
    { id: "c-24", name: "Karen Lewis", phone: "+1 (571) 555-0124", lastService: "Junk Removal", tags: ["Completed", "Eligible"] },
    { id: "c-25", name: "Eric Robinson", phone: "+1 (703) 555-0125", lastService: "Furniture Removal", tags: ["Completed", "No Request Sent"] },
  ],
  events: [
    {
      id: "evt-1",
      event_type: "sent",
      channel: "sms",
      customer_name: "Jane Smith",
      customer_phone: "+15551234001",
      service_type: "Junk Removal",
      created_at: daysAgo(1),
    },
    {
      id: "evt-2",
      event_type: "sent",
      channel: "email",
      customer_name: "Marcus Lee",
      customer_email: "marcus@example.com",
      service_type: "Hauling",
      created_at: daysAgo(2),
    },
  ],
  keywordSuggestions: [
    { id: "kw1", keyword: "junk removal", keyword_type: "service", gap: 18 },
    { id: "kw2", keyword: "same-day service", keyword_type: "theme", gap: 14 },
    { id: "kw3", keyword: "professional crew", keyword_type: "theme", gap: 12 },
    { id: "kw4", keyword: "garage cleanout", keyword_type: "service", gap: 9 },
    { id: "kw5", keyword: "furniture haul away", keyword_type: "service", gap: 8 },
  ],
};

export const reviewRequestsPreviewStats = {
  total_sent: 248,
  total_sent_trend: 18,
  email_sent: 138,
  sms_sent: 94,
  manual_sent: 16,
  failed: 5,
  delivery_rate: 98,
  delivery_rate_trend: 2,
  last_7_days: 42,
  last_7_days_trend: 17,
  last_30_days: 248,
  replies: 51,
  reviews_generated: 18,
  reviews_generated_trend: 28,
  review_link_clicks: 42,
  review_link_clicks_trend: 17,
  conversion_rate: 7.3,
  conversion_rate_trend: 1.2,
  inbound_reply_domain: "reply.mapsgrowth.app",
  trial_sms_template: null,
  recent_sends: [
    {
      id: "send-1",
      channel: "sms",
      recipient_email: null,
      recipient_phone: "+1 (571) 555-0101",
      status: "sent",
      message_body: "Hi James — thanks for choosing Premier Junk Removal! Leave a quick Google review…",
      sent_at: daysAgo(0),
      created_at: daysAgo(0),
      has_reply: false,
      review_request_contacts: { customer_name: "James Whitfield" },
    },
    {
      id: "send-2",
      channel: "sms",
      recipient_email: null,
      recipient_phone: "+1 (571) 555-0102",
      status: "sent",
      message_body: "Hi Maria — thanks for choosing Premier Junk Removal! Review link…",
      sent_at: daysAgo(1),
      created_at: daysAgo(1),
      has_reply: true,
      review_request_contacts: { customer_name: "Maria Santos" },
    },
    {
      id: "send-3",
      channel: "sms",
      recipient_email: null,
      recipient_phone: "+1 (703) 555-0103",
      status: "sent",
      message_body: "Hi Tyler — appreciate your business. Quick Google review?",
      sent_at: daysAgo(2),
      created_at: daysAgo(2),
      has_reply: false,
      review_request_contacts: { customer_name: "Tyler Brooks" },
    },
    {
      id: "send-4",
      channel: "email",
      recipient_email: "priya@example.com",
      recipient_phone: null,
      status: "failed",
      message_body: "Hi Priya — we'd love your feedback on Google…",
      sent_at: daysAgo(3),
      created_at: daysAgo(3),
      has_reply: false,
      review_request_contacts: { customer_name: "Priya Patel" },
    },
    {
      id: "send-5",
      channel: "sms",
      recipient_email: null,
      recipient_phone: "+1 (703) 555-0105",
      status: "sent",
      message_body: "Hi Devon — thanks for the service. Quick review?",
      sent_at: daysAgo(4),
      created_at: daysAgo(4),
      has_reply: true,
      review_request_contacts: { customer_name: "Devon Clarke" },
    },
  ],
};

export const reviewRequestsPreviewCampaigns = {
  campaigns: [
    {
      id: "camp-1",
      name: "June Closed Jobs",
      status: "active",
      channel: "both",
      created_at: daysAgo(12),
      recipients_total: 84,
      recipients_ready: 76,
      queued: 18,
      sent: 52,
      failed: 3,
      clicked: 21,
      opted_out: 2,
    },
    {
      id: "camp-2",
      name: "HOA Cleanouts Batch",
      status: "paused",
      channel: "email",
      created_at: daysAgo(20),
      recipients_total: 40,
      recipients_ready: 38,
      queued: 0,
      sent: 22,
      failed: 1,
      clicked: 9,
      opted_out: 1,
    },
    {
      id: "camp-3",
      name: "Spring Garage Sweep",
      status: "completed",
      channel: "sms",
      created_at: daysAgo(45),
      recipients_total: 55,
      recipients_ready: 55,
      queued: 0,
      sent: 54,
      failed: 1,
      clicked: 17,
      opted_out: 0,
    },
  ],
};

export { now };
